import { Question } from '@/types';

export const BIOLOGY_QUESTIONS: Question[] = [
  {
    id: 'bio-01',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Molecular Genetics: Replication, Transcription, Translation',
    difficulty: 'hard',
    question: 'A segment of double-stranded DNA contains 1,200 nucleotides, of which 220 are Adenine. How many phosphodiester bonds and how many total hydrogen bonds are present in this DNA duplex?',
    options: [
      '1,198 phosphodiester bonds and 1,580 hydrogen bonds',
      '1,200 phosphodiester bonds and 1,420 hydrogen bonds',
      '1,198 phosphodiester bonds and 1,760 hydrogen bonds',
      '599 phosphodiester bonds and 1,580 hydrogen bonds'
    ],
    correctAnswer: 0,
    explanation: '1. In a linear double-stranded DNA with $N$ total nucleotides, there are two polynucleotide chains. Each single strand of $N/2 = 600$ nucleotides has $(600 - 1) = 599$ phosphodiester bonds. Total phosphodiester bonds = $2 \\times 599 = N - 2 = 1,198$. 2. By Chargaff rule: $A = T = 220$. Total $A+T = 440$. Remaining nucleotides are $G+C = 1,200 - 440 = 760$. Since $G = C$, each is $760 / 2 = 380$. $A-T$ pairs have 2 hydrogen bonds ($220 \\times 2 = 440$) and $G-C$ pairs have 3 hydrogen bonds ($380 \\times 3 = 1,140$). Total hydrogen bonds = $440 + 1,140 = 1,580$.',
    solution: '1. Phosphodiester bonds in linear duplex $= N - 2 = 1,200 - 2 = 1,198$.\n2. $A = 220 \\implies T = 220$.\n3. $G = C = (1,200 - 440)/2 = 380$.\n4. H-bonds $= 2(220) + 3(380) = 440 + 1,140 = 1,580$.',
    concepts: ['Chargaff rule', 'Phosphodiester linkages in linear dsDNA', 'Hydrogen bonding between base pairs'],
    commonTrap: 'Thinking total phosphodiester bonds is $N-1$ (which applies only to a single strand). A duplex has 2 strands, so $N-2$.',
    shortcut: 'Linear duplex: Phosphodiester bonds = $N - 2 = 1198$. H-bonds = $2A + 3G = 2(220) + 3(380) = 1580$.',
    hints: ['How many free ends are there in a linear double-stranded DNA molecule?', 'Apply Chargaff rule $A = T$ and $G = C$ to find the number of Guanine nucleotides.', 'Multiply $A-T$ pairs by 2 and $G-C$ pairs by 3.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'bio-02',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Molecular Genetics: Replication, Transcription, Translation',
    difficulty: 'elite',
    originalPastQuestionId: 'bio-01',
    question: 'A closed circular plasmid DNA molecule of $3,600$ base pairs undergoes semiconservative replication in an in-vitro system where all Cytosine nucleotides in the reaction mixture are labeled with $^{32}\\text{P}$ at their $\\alpha$-phosphate. The original plasmid contained $30\\%$ Guanine. After 2 complete rounds of replication, what is the total number of radiolabeled phosphodiester bonds formed in the daughter plasmids, and what fraction of all plasmids will carry at least one radioactive strand?',
    options: [
      '$6,480$ radiolabeled bonds; fraction is $100\\%$ ($4/4$ plasmids)',
      '$4,320$ radiolabeled bonds; fraction is $100\\%$ ($4/4$ plasmids)',
      '$2,160$ radiolabeled bonds; fraction is $75\\%$ ($3/4$ plasmids)',
      '$3,240$ radiolabeled bonds; fraction is $50\\%$ ($2/4$ plasmids)'
    ],
    correctAnswer: 0,
    explanation: '1. Plasmid length = 3,600 bp = 7,200 nucleotides per duplex. Guanine = 30% $\\implies$ Cytosine = 30%. Number of Cytosines per plasmid duplex = $0.30 \\times 7,200 = 2,160$ (or 1,080 Cytosines per single strand). 2. In DNA polymerization, the $\\alpha$-phosphate of the incoming dCTP forms the phosphodiester bond. 3. After 2 rounds of replication, 1 parent plasmid produces $2^2 = 4$ daughter plasmids (total 8 strands). Exactly 2 strands are the original non-radioactive parent strands, while $8 - 2 = 6$ strands were synthesized de novo from the radioactive substrate. 4. Total radioactive Cytosines incorporated in the 6 newly made strands = $6 \\times 1,080 = 6,480$ radiolabeled bonds. 5. Semiconservative segregation distributes the 2 parent strands into 2 separate hybrid plasmids; the remaining 2 plasmids consist entirely of newly synthesized radioactive strands. Therefore, ALL 4 plasmids ($100\\%$) contain radioactivity.',
    solution: '1. Total strands after 2 rounds: $2^2 \\times 2 = 8$ strands.\n2. New strands synthesized in $^{32}\\text{P}$: $8 - 2 = 6$ strands.\n3. Cytosine per strand: $1,080$.\n4. Labeled phosphodiester bonds: $6 \\times 1,080 = 6,480$.\n5. All 4 plasmids contain at least one newly synthesized strand $\\implies 100\\%$.',
    concepts: ['Meselson-Stahl semiconservative replication', 'Alpha-phosphate incorporation in DNA synthesis', 'Plasmid replication rounds'],
    commonTrap: 'Thinking only 50% or 75% carry radioactive strands. Because we started with only 2 non-radioactive strands, at least 1 radioactive strand is present in every single one of the 4 plasmids.',
    shortcut: '6 newly made strands $\\times 1080 = 6480$. All 4 plasmids contain newly made strands ($100\\%$).',
    hints: ['How many total single strands are present in 4 daughter plasmids?', 'How many of those strands are newly synthesized in the radioactive medium?', 'Remember that the 2 original strands end up in only 2 plasmids, leaving the other 2 fully labeled.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 110
  },
  {
    id: 'bio-03',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Endocrine System & Hormonal Control',
    difficulty: 'hard',
    question: 'A patient presents with severe hyperkalemia, hyponatremia, metabolic acidosis, hypotension, and generalized hyperpigmentation of the buccal mucosa and skin creases. Which endocrine pathology is the primary cause?',
    options: [
      'Primary Adrenocortical Insufficiency (Addison disease)',
      'Secondary Adrenocortical Insufficiency due to anterior pituitary infarct',
      'Conn syndrome (Primary hyperaldosteronism)',
      'Cushing disease due to ACTH-secreting pituitary adenoma'
    ],
    correctAnswer: 0,
    explanation: 'Primary adrenal insufficiency (Addison disease) involves autoimmune destruction of the entire adrenal cortex. Lack of aldosterone impairs renal $Na^+$ reabsorption and $K^+/H^+$ excretion, resulting in hyponatremia, hyperkalemia, metabolic acidosis, and hypotension. The lack of cortisol removes negative feedback on the hypothalamus and pituitary, leading to high compensatory levels of ACTH and its precursor pro-opiomelanocortin (POMC), which contains $\\alpha$-MSH (Melanocyte-Stimulating Hormone), driving pathognomonic buccal and palmar hyperpigmentation. In secondary insufficiency, pituitary failure means ACTH is low, so hyperpigmentation never occurs.',
    solution: '1. Aldosterone deficiency $\\implies$ hyponatremia, hyperkalemia, acidosis, hypotension.\n2. Cortisol deficiency $\\implies$ loss of negative feedback $\\implies$ high ACTH/POMC.\n3. $\\alpha$-MSH domain in POMC stimulates melanocytes $\\implies$ hyperpigmentation.\n4. Hyperpigmentation confirms Primary Adrenocortical Insufficiency (Addison disease).',
    concepts: ['Adrenal cortex hormones', 'Negative feedback axis', 'POMC and MSH physiology'],
    commonTrap: 'Confusing primary with secondary adrenal insufficiency. Secondary insufficiency has LOW ACTH, so hyperpigmentation is completely absent.',
    shortcut: 'Hyperpigmentation + Hyperkalemia + Hyponatremia = Addison disease (Primary adrenal failure).',
    hints: ['Notice the electrolyte imbalance: high potassium and low sodium indicate aldosterone deficiency.', 'Why would the patient develop hyperpigmentation? Look at the precursor for ACTH.', 'Does secondary pituitary failure cause high or low ACTH?'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'bio-04',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Circulation, Cardiac Cycle & Blood',
    difficulty: 'hard',
    question: 'In a standard 12-lead Electrocardiogram (ECG), the **T-wave** represents which physiological cardiac event?',
    options: [
      'Ventricular repolarization',
      'Ventricular depolarization',
      'Atrial repolarization',
      'Atrial depolarization'
    ],
    correctAnswer: 0,
    explanation: 'In a normal cardiac cycle: (1) **P-wave** represents atrial depolarization (spreading of impulse from SA node through atria). (2) **QRS complex** represents ventricular depolarization (and masks the simultaneous atrial repolarization). (3) **T-wave** represents ventricular repolarization (the recovery and relaxation of ventricles as $K^+$ channels open to restore the negative resting potential).',
    solution: '1. P-wave = Atrial depolarization.\n2. QRS complex = Ventricular depolarization.\n3. T-wave = Ventricular repolarization.',
    concepts: ['ECG waveform interpretation', 'Cardiac electrical cycle', 'Ventricular repolarization'],
    commonTrap: 'Thinking T-wave represents atrial repolarization or ventricular depolarization.',
    shortcut: 'P = Atrial Depol, QRS = Ventricular Depol, T = Ventricular Repol.',
    hints: ['P-wave comes first: what chambers contract first?', 'QRS is large and sharp: what massive muscle mass is depolarizing?', 'T-wave is the dome at the end: recovery of the ventricles.'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 35
  },
  {
    id: 'bio-05',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Circulation, Cardiac Cycle & Blood',
    difficulty: 'very_hard',
    question: 'During a cardiac cycle of total duration $0.8\\,\\text{seconds}$, the duration of **isovolumetric ventricular contraction** is approximately $0.05\\,\\text{s}$. During this specific phase, which of the following mechanical states is TRUE?',
    options: [
      'All four cardiac valves (AV and semilunar) are closed, and ventricular pressure rises sharply without volume change',
      'AV valves are open and semilunar valves are closed while blood rapidly enters ventricles',
      'Semilunar valves open immediately while AV valves remain open',
      'Ventricular volume decreases rapidly while intraventricular pressure remains constant'
    ],
    correctAnswer: 0,
    explanation: 'Isovolumetric ventricular contraction begins immediately after ventricular depolarization causes the ventricles to contract. As ventricular pressure exceeds atrial pressure, the atrioventricular (AV) valves (mitral and tricuspid) snap shut, producing the first heart sound ($S_1$). However, ventricular pressure is not yet high enough to exceed the diastolic pressure in the aorta and pulmonary artery, so the semilunar valves remain firmly shut. With all four valves closed, the ventricles contract against an incompressible liquid: ventricular pressure rises steeply, but ventricular blood volume remains completely constant (isovolumetric).',
    solution: '1. $S_1$ sound marks AV valve closure.\n2. Semilunar valves have not yet opened (ventricular pressure < aortic pressure).\n3. All 4 valves closed $\\implies$ volume constant, pressure spikes rapidly.',
    concepts: ['Cardiac cycle phases', 'Wiggers diagram', 'Isovolumetric contraction mechanics'],
    commonTrap: 'Thinking semilunar valves open the moment the ventricles start contracting.',
    shortcut: '"Isovolumetric" literally means volume does not change, which can only happen if ALL valves are closed.',
    hints: ['Break down the word "iso-volumetric": what does it imply about volume?', 'Have the semilunar valves opened yet?', 'What happens to pressure when muscle contracts around a closed fluid chamber?'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'bio-06',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Cell Biology & Biomolecules',
    topic: 'Cell Cycle & Cell Division (Mitosis / Meiosis)',
    difficulty: 'hard',
    question: 'During Meiosis I Prophase, crossing over between non-sister chromatids of homologous chromosomes is mediated by the enzyme recombinase during which sub-stage?',
    options: [
      'Pachytene',
      'Zygotene',
      'Diplotene',
      'Diakinesis'
    ],
    correctAnswer: 0,
    explanation: 'Prophase I stages: (1) **Leptotene**: Chromatin condensation, bouquet stage. (2) **Zygotene**: Synapsis of homologous chromosomes, synaptonemal complex formation. (3) **Pachytene**: Recombination nodules appear; crossing over occurs between non-sister chromatids mediated by enzyme recombinase. (4) **Diplotene**: Dissolution of synaptonemal complex, X-shaped chiasmata become visible. (5) **Diakinesis**: Terminalization of chiasmata.',
    solution: '1. Zygotene = Synapsis.\n2. Pachytene = Crossing over (recombinase).\n3. Diplotene = Chiasmata appearance.\n4. Diakinesis = Terminalization.',
    concepts: ['Meiosis Prophase I sub-stages', 'Synaptonemal complex', 'Recombinase-mediated crossing over'],
    commonTrap: 'Confusing Pachytene (where crossing over actually occurs) with Diplotene (where chiasmata first become visible as chromosomes separate).',
    shortcut: 'Mnemonic: LZPDD. P = Pachytene = Pac-crossing over.',
    hints: ['Synapsis occurs in Zygotene.', 'Crossing over occurs in the middle stage with recombination nodules.', 'Chiasmata become visible in the following stage (Diplotene).'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'bio-07',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Excretory System & Counter-Current Mechanism',
    difficulty: 'hard',
    question: 'In the human nephron, which segment is **permeable to water** but almost completely impermeable to electrolytes, leading to progressive hypertonicity of the tubular fluid?',
    options: [
      'Descending limb of the Loop of Henle',
      'Ascending thin limb of the Loop of Henle',
      'Thick ascending limb of the Loop of Henle',
      'Early distal convoluted tubule'
    ],
    correctAnswer: 0,
    explanation: 'The descending thin limb of the Loop of Henle has high expression of aquaporin-1 water channels and is highly permeable to water, but lacks active ion transporters and has very low permeability to $Na^+$ and $Cl^-$. As tubular fluid descends into the hyperosmotic renal medulla, water is drawn out by osmosis into the medullary interstitium, concentrating the urine up to $1,200\\,\\text{mOsm/L}$. In contrast, the ascending limb is completely impermeable to water and actively pumps out $Na^+/K^+/2Cl^-$.',
    solution: '1. Descending limb: Permeable to water, impermeable to ions $\\implies$ fluid concentrates.\n2. Ascending limb: Impermeable to water, active ion transport $\\implies$ fluid dilutes (diluting segment).',
    concepts: ['Counter-current multiplier in Loop of Henle', 'Aquaporin expression in nephron', 'Medullary osmotic gradient'],
    commonTrap: 'Confusing descending limb (water out) with ascending limb (ions out, water impermeable).',
    shortcut: 'Descending limb = Water permeable (concentrates); Ascending limb = Water impermeable (dilutes).',
    hints: ['Which limb allows water to leave into the salty renal medulla?', 'Is the ascending limb permeable or impermeable to water?', 'Remember that the ascending limb is the diluting segment.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'bio-08',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Excretory System & Counter-Current Mechanism',
    difficulty: 'very_hard',
    question: 'A pharmacologist administers a potent drug that selectively blocks the $\\text{Na}^+\\text{-K}^+\\text{-2Cl}^-$ (NKCC2) cotransporter in the thick ascending limb of the Loop of Henle (loop diuretic like furosemide). What is the physiological consequence on medullary osmolarity and maximal urinary concentrating capacity?',
    options: [
      'Abolishes the corticomedullary osmotic gradient, severely reducing the kidney maximal concentrating capacity',
      'Increases medullary osmolarity and produces highly concentrated hypertonic urine',
      'Selectively blocks water reabsorption in the proximal convoluted tubule',
      'Increases ADH secretion and stimulates aquaporin-2 insertion in collecting ducts'
    ],
    correctAnswer: 0,
    explanation: 'Active reabsorption of $Na^+, K^+$, and $Cl^-$ via NKCC2 in the thick ascending limb is the primary engine driving the counter-current multiplier system that establishes and maintains the hypertonic medullary interstitium ($300 \\to 1,200\\,\\text{mOsm/kg}$). Blocking NKCC2 with furosemide halts active ion deposition into the interstitium, dissipating the corticomedullary osmotic gradient. Without this hypertonic gradient, water cannot be reabsorbed from collecting ducts even in the presence of ADH, causing massive diuresis with inability to concentrate urine.',
    solution: '1. NKCC2 pumps ions into the medullary interstitium without water.\n2. Blocking NKCC2 dissipates the hyperosmotic medullary gradient.\n3. Water cannot be reabsorbed downstream in collecting ducts $\\implies$ severe loss of concentrating ability.',
    concepts: ['NKCC2 cotransporter mechanism', 'Loop diuretic pharmacology', 'Dissipation of counter-current multiplier gradient'],
    commonTrap: 'Thinking loop diuretics work on the collecting duct (where aldosterone and ADH act).',
    shortcut: 'Block NKCC2 $\\implies$ destroy medullary gradient $\\implies$ urine cannot be concentrated $\\implies$ massive water loss.',
    hints: ['What transporter establishes the hyperosmotic salt gradient in the renal medulla?', 'If the salt pump in the thick ascending limb is blocked, what happens to interstitial osmolarity?', 'Can collecting ducts draw water out if the surrounding medulla is not hypertonic?'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 65
  },
  {
    id: 'bio-09',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Plant Physiology',
    topic: 'Photosynthesis (C3, C4, CAM Pathways)',
    difficulty: 'hard',
    question: 'In $C_4$ plants (e.g. maize, sugarcane), the primary $\\text{CO}_2$ acceptor and the first stable $4\\text{-carbon}$ carboxylation product formed in mesophyll cells are, respectively:',
    options: [
      'Phosphoenolpyruvate (PEP) and Oxaloacetic acid (OAA)',
      'Ribulose-1,5-bisphosphate (RuBP) and 3-Phosphoglycerate (3-PGA)',
      'Phosphoenolpyruvate (PEP) and Malic acid',
      'Pyruvate and Oxaloacetic acid (OAA)'
    ],
    correctAnswer: 0,
    explanation: 'In $C_4$ plants, atmospheric $\\text{CO}_2$ is initially fixed in the cytoplasm of mesophyll cells by the enzyme PEP carboxylase. The primary $\\text{CO}_2$ acceptor molecule is the 3-carbon compound Phosphoenolpyruvate (PEP). The addition of $\\text{HCO}_3^-$ to PEP yields the first stable 4-carbon intermediate Oxaloacetic acid (OAA), which is subsequently reduced to malate or aspartate before transport into bundle sheath cells.',
    solution: '1. Mesophyll cell primary acceptor: Phosphoenolpyruvate (PEP, 3C).\n2. Enzyme: PEP carboxylase.\n3. First stable product: Oxaloacetic acid (OAA, 4C).\n4. RuBisCO fixes CO2 later in bundle sheath cells.',
    concepts: ['C4 pathway biochemistry', 'PEP carboxylase affinity', 'Kranz anatomy division of labor'],
    commonTrap: 'Selecting RuBP (which is the primary acceptor in C3 plants and in bundle sheath cells, but NOT in mesophyll cells of C4 plants).',
    shortcut: 'C4 mesophyll: Acceptor = PEP (3C); First stable product = OAA (4C).',
    hints: ['What 3-carbon molecule acts as the substrate for PEP carboxylase?', 'What is the 4-carbon dicarboxylic acid formed after carboxylation?', 'Do not confuse C3 RuBP with C4 PEP.'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'bio-10',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Plant Physiology',
    topic: 'Photosynthesis (C3, C4, CAM Pathways)',
    difficulty: 'very_hard',
    question: 'Why do $C_4$ plants show significantly higher photosynthetic efficiency and biomass yield under high light intensity and elevated temperatures compared to $C_3$ plants?',
    options: [
      'Kranz anatomy concentrates $\\text{CO}_2$ around RuBisCO in bundle sheath cells, completely suppressing the oxygenase activity and photorespiration',
      'They produce 4 molecules of ATP per photon absorbed',
      'They do not require water for photolysis in photosystem II',
      'Their stomata remain completely closed during the day like CAM plants'
    ],
    correctAnswer: 0,
    explanation: 'RuBisCO has dual affinity for $\\text{CO}_2$ and $\\text{O}_2$. At high temperatures, the solubility of $\\text{CO}_2$ drops faster than $\\text{O}_2$, and RuBisCO oxygenase activity rises, wasting up to $25-40\\%$ of fixed carbon in photorespiration ($C_2$ cycle) in $C_3$ plants. $C_4$ plants overcome this via Kranz anatomy: mesophyll cells pump malate into bundle sheath cells where decarboxylation creates a high local concentration of $\\text{CO}_2$. This saturates RuBisCO active sites with $\\text{CO}_2$, completely preventing photorespiration.',
    solution: '1. Photorespiration is the wasteful oxygenase reaction of RuBisCO in C3 plants.\n2. C4 plants use a CO2-concentrating pump mechanism via Kranz anatomy.\n3. High CO2 in bundle sheath cells suppresses RuBisCO oxygenase activity completely.',
    concepts: ['Photorespiration suppression', 'RuBisCO carboxylase vs oxygenase kinetics', 'Kranz anatomy function'],
    commonTrap: 'Thinking C4 plants have an entirely different enzyme replacing RuBisCO for carbohydrate synthesis. RuBisCO is still the final fixing enzyme in bundle sheath cells!',
    shortcut: 'C4 advantage = CO2 concentrating pump in bundle sheath cells = zero photorespiration.',
    hints: ['What wasteful process consumes ATP in C3 plants at high temperatures?', 'How does Kranz anatomy affect the CO2/O2 ratio around RuBisCO?', 'Can RuBisCO bind oxygen if CO2 is present at high concentration?'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'bio-11',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Molecular Genetics: Replication, Transcription, Translation',
    difficulty: 'hard',
    question: 'In the *lac* operon of *E. coli*, when both glucose and lactose are present in the growth medium in high concentrations, the transcription of the operon is:',
    options: [
      'Exceedingly low (basal level) due to catabolite repression (low cAMP-CAP complex)',
      'Maximal because lactose inducers are present',
      'Completely terminated by rho-factor',
      'Permanently repressed by corepressor tryptophan'
    ],
    correctAnswer: 0,
    explanation: 'Transcription of the *lac* operon requires two conditions: (1) Lactose must be present to produce allolactose, which binds and inactivates the Lac repressor. (2) Glucose must be absent: high glucose inhibits adenylate cyclase, resulting in very low cellular levels of cyclic AMP ($c\\text{AMP}$). Without $c\\text{AMP}$, the CAP (Catabolite Activator Protein) cannot bind to the promoter to recruit RNA polymerase effectively. Even though the repressor is off, transcription remains at a minimal basal level due to catabolite repression.',
    solution: '1. Lactose present $\\implies$ Lac repressor inactivated (derepression).\n2. Glucose present $\\implies$ Adenylate cyclase inhibited $\\implies$ low cAMP.\n3. CAP cannot bind without cAMP $\\implies$ RNA polymerase binds poorly.\n4. Result: Basal, exceedingly low transcription (catabolite repression).',
    concepts: ['Lac operon regulation', 'Positive control via cAMP-CAP', 'Catabolite repression by glucose'],
    commonTrap: 'Thinking that lactose presence alone guarantees high transcription. High glucose overrides lactose induction by starving the promoter of cAMP-CAP!',
    shortcut: 'High glucose = Low cAMP = No CAP binding = Negligible transcription (even with lactose).',
    hints: ['What effect does glucose have on intracellular cAMP levels?', 'Is cAMP-CAP required for high-level RNA polymerase recruitment?', 'What is the term for preferential utilization of glucose over lactose?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'bio-12',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Mendelian Genetics & Linkage',
    difficulty: 'hard',
    question: 'A hemophilic man marries a phenotypically normal woman whose father was hemophilic. What is the probability that their first child will be a hemophilic daughter?',
    options: [
      '$25\\%$ ($1/4$)',
      '$50\\%$ ($1/2$)',
      '$0\\%$',
      '$12.5\\%$ ($1/8$)'
    ],
    correctAnswer: 0,
    explanation: 'Hemophilia is an X-linked recessive disorder ($X^h$). 1. Father is hemophilic: genotype is $X^h Y$. 2. Mother is phenotypically normal but her father was hemophilic ($X^h Y$), so she must have inherited an $X^h$ chromosome from him, making her an obligate carrier: genotype $X^H X^h$. 3. Possible offspring: Daughters receive $X^h$ from the father and either $X^H$ (carrier, $X^H X^h$) or $X^h$ (hemophilic, $X^h X^h$) from the mother. Probability of having a daughter = $1/2$. Probability that a daughter inherits $X^h$ from mother = $1/2$. Therefore, probability of a hemophilic daughter among all possible children is $1/2 \\times 1/2 = 1/4 = 25\\%$.',
    solution: '1. Father: $X^h Y$.\n2. Mother: $X^H X^h$ (carrier).\n3. Punnett square: $X^H X^h$ (normal carrier girl, 25%), $X^h X^h$ (hemophilic girl, 25%), $X^H Y$ (normal boy, 25%), $X^h Y$ (hemophilic boy, 25%).\n4. Probability of hemophilic daughter among ALL children $= 1/4 = 25\\%$.',
    concepts: ['X-linked recessive inheritance', 'Carrier female pedigree deduction', 'Compound probability of sex and phenotype'],
    commonTrap: 'Confusing "probability among daughters" (which would be $50\\%$) with "probability that their first child is a hemophilic daughter" (which is $25\\%$).',
    shortcut: 'Carrier mother $\\times$ Hemophilic father: $P(\\text{daughter}) = 1/2$, $P(\\text{hemophilic} | \\text{daughter}) = 1/2 \\implies 1/2 \\times 1/2 = 25\\%$.',
    hints: ['Deduce the mother genotype: her father had hemophilia.', 'Construct the Punnett square for $X^h Y \\times X^H X^h$.', 'The question asks for a hemophilic daughter among ALL possible children.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'bio-13',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Mendelian Genetics & Linkage',
    difficulty: 'very_hard',
    question: 'In a dihybrid test cross ($AaBb \\times aabb$), the observed offspring numbers are: $AB = 410$, $ab = 390$, $Ab = 100$, and $aB = 100$. The recombination frequency and map distance between genes $A$ and $B$ are:',
    options: [
      '$20\\%$ and $20\\,\\text{cM}$',
      '$10\\%$ and $10\\,\\text{cM}$',
      '$40\\%$ and $40\\,\\text{cM}$',
      '$50\\%$ and independent assortment'
    ],
    correctAnswer: 0,
    explanation: '1. Total offspring $= 410 + 390 + 100 + 100 = 1000$. 2. Parental phenotypes are the two most frequent classes: $AB$ ($410$) and $ab$ ($390$), total $= 800$. 3. Recombinant phenotypes are the two least frequent non-parental classes: $Ab$ ($100$) and $aB$ ($100$), total recombinants $= 100 + 100 = 200$. 4. Recombination frequency (RF) $= \\frac{\\text{Total Recombinants}}{\\text{Total Offspring}} \\times 100\\% = \\frac{200}{1000} \\times 100\\% = 20\\%$. 5. Since $1\\%$ recombination frequency equals $1\\,\\text{centiMorgan}$ ($1\\,\\text{cM}$ or map unit), the map distance is $20\\,\\text{cM}$.',
    solution: '1. Total progeny $= 1,000$.\n2. Recombinants $= 100 + 100 = 200$.\n3. Recombination frequency $= (200 / 1000) \\times 100\\% = 20\\%$.\n4. Map distance $= 20\\,\\text{cM}$.',
    concepts: ['Morgan linkage mapping', 'Recombination frequency calculation', 'centiMorgan (cM) definition'],
    commonTrap: 'Summing parental classes instead of recombinant classes, or dividing by individual parental frequencies.',
    shortcut: 'Recombinants = 200 out of 1000 = 20% = 20 cM.',
    hints: ['Identify the recombinant classes: they are the two least frequent phenotypes.', 'Divide total recombinants by total progeny.', 'Convert the percentage directly to centiMorgans (cM).'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 50
  },
  {
    id: 'bio-14',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Cell Biology & Biomolecules',
    topic: 'Cell Organelles & Endomembrane System',
    difficulty: 'hard',
    question: 'Which of the following organelles contains its own $70\\text{S}$ ribosomes, circular naked DNA, and divides by binary fission, supporting the Endosymbiotic Theory?',
    options: [
      'Mitochondria and Chloroplasts',
      'Lysosomes and Peroxisomes',
      'Golgi apparatus and Endoplasmic Reticulum',
      'Centrioles and Ribosomes'
    ],
    correctAnswer: 0,
    explanation: 'According to the Endosymbiotic Theory (proposed by Lynn Margulis), mitochondria and chloroplasts originated as free-living prokaryotic aerobic bacteria and cyanobacteria that were engulfed by ancestral anaerobic eukaryotic host cells. Distinct prokaryotic features preserved in both organelles include: (1) circular, double-stranded DNA lacking histones, (2) prokaryotic-sized $70\\text{S}$ ribosomes (unlike the $80\\text{S}$ cytosolic ribosomes of eukaryotes), (3) double-membrane envelope with bacterial-like cardiolipin in the inner membrane, and (4) autonomous division by binary fission.',
    solution: '1. Both mitochondria and chloroplasts possess autonomous circular DNA.\n2. Both contain 70S ribosomes.\n3. Both divide by binary fission independently of nuclear division.',
    concepts: ['Endosymbiotic Theory', '70S vs 80S ribosomes', 'Semi-autonomous organelles'],
    commonTrap: 'Thinking peroxisomes are endosymbionts. Peroxisomes reproduce by fission but do NOT contain their own DNA or ribosomes.',
    shortcut: 'Mitochondria + Chloroplast = Semi-autonomous organelles = 70S ribosomes + circular DNA.',
    hints: ['Which organelles are considered semi-autonomous?', 'Look for organelles with prokaryotic-style 70S ribosomes and circular DNA.', 'Lysosomes and peroxisomes have no genetic material.'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 35
  },
  {
    id: 'bio-15',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Nervous System & Nerve Impulse Conduction',
    difficulty: 'hard',
    question: 'During the generation of an action potential in a myelinated neuron, the rapid upstroke of **depolarization** is mediated by:',
    options: [
      'Rapid influx of $Na^+$ through voltage-gated $Na^+$ channels',
      'Efflux of $K^+$ through voltage-gated $K^+$ channels',
      'Active pumping of $3\\,Na^+$ outward by the $Na^+/K^+$ ATPase pump',
      'Influx of $Cl^-$ through ligand-gated channels'
    ],
    correctAnswer: 0,
    explanation: 'At resting membrane potential ($-70\\,\\text{mV}$), voltage-gated sodium channels are closed. When a threshold stimulus (approx $-55\\,\\text{mV}$) depolarizes the axon hillock, the activation gates of voltage-gated $Na^+$ channels open rapidly. Driven by both concentration gradient and electrical attraction, $Na^+$ ions rush into the intracellular axoplasm. This massive positive charge influx causes rapid depolarization, reversing the membrane potential up to $+30\\,\\text{mV}$. Repolarization subsequently occurs when $Na^+$ channels inactivate and voltage-gated $K^+$ channels open, allowing $K^+$ efflux.',
    solution: '1. Resting potential: $-70\\,\\text{mV}$.\n2. Threshold reached $\\implies$ Voltage-gated $Na^+$ channels open.\n3. Influx of $Na^+$ causes depolarization up to $+30\\,\\text{mV}$.',
    concepts: ['Nerve impulse depolarization', 'Voltage-gated sodium channels', 'Hodgkin-Huxley ionic basis'],
    commonTrap: 'Confusing depolarization ($Na^+$ influx) with repolarization ($K^+$ efflux) or maintenance of resting potential ($Na^+/K^+$ ATPase).',
    shortcut: 'Depolarization = $Na^+$ in; Repolarization = $K^+$ out.',
    hints: ['What ion moves inside the cell to make the interior positive?', 'Are these channels voltage-gated or ATP pumps?', 'Remember: $Na^+$ rushes in during the rising phase.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'bio-16',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Nervous System & Nerve Impulse Conduction',
    difficulty: 'elite',
    question: 'Tetrodotoxin (TTX), a neurotoxin from the pufferfish, selectively blocks voltage-gated sodium channels. What is the immediate effect of applying TTX to an isolated giant squid axon during electrical stimulation?',
    options: [
      'Complete abolition of the action potential without altering the resting membrane potential',
      'Prolonged depolarization due to inability to repolarize',
      'Immediate collapse of the resting potential from $-70\\,\\text{mV}$ to $0\\,\\text{mV}$',
      'Spontaneous firing of continuous high-frequency action potentials'
    ],
    correctAnswer: 0,
    explanation: 'Tetrodotoxin binds with high affinity to the outer pore of voltage-gated sodium channels, preventing $Na^+$ conductance. Without $Na^+$ influx, the threshold depolarization cannot trigger the regenerative rising phase, completely abolishing action potential generation. However, resting membrane potential ($-70\\,\\text{mV}$) is determined primarily by resting $K^+$ leak channels and the electrogenic $Na^+/K^+$ ATPase, neither of which is inhibited by TTX. Thus, the resting potential remains normal while excitability is completely silenced.',
    solution: '1. TTX blocks voltage-gated $Na^+$ channels.\n2. Action potentials require voltage-gated $Na^+$ influx $\\implies$ action potential abolished.\n3. Resting potential depends on $K^+$ leak channels and $Na^+/K^+$ ATPase, which are unaffected by TTX $\\implies$ resting potential unchanged.',
    concepts: ['Tetrodotoxin pharmacology', 'Voltage-gated vs leak channels', 'Resting potential vs action potential generation'],
    commonTrap: 'Thinking that blocking sodium channels destroys the resting potential. Resting potential is governed by potassium leak channels and the sodium pump!',
    shortcut: 'TTX blocks voltage-gated $Na^+$ channels $\\implies$ no action potential, but resting potential remains intact.',
    hints: ['What channels are responsible for the action potential upstroke?', 'What channels maintain the resting membrane potential?', 'TTX blocks only voltage-gated $Na^+$ channels.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 65
  },
  {
    id: 'bio-17',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Plant Physiology',
    topic: 'Plant Hormones (Auxin, Cytokinin, Gibberellin, ABA, Ethylene)',
    difficulty: 'hard',
    question: 'During drought stress, rapid stomatal closure in plants is directly mediated by which phytohormone acting on guard cells?',
    options: [
      'Abscisic Acid (ABA)',
      'Auxin (IAA)',
      'Gibberellic Acid ($GA_3$)',
      'Cytokinin (Zeatin)'
    ],
    correctAnswer: 0,
    explanation: 'Abscisic acid (ABA) is the classic plant "stress hormone". Under soil water deficit, ABA synthesized in roots is transported via xylem to leaves, where it binds to PYR/PYL/RCAR receptors in guard cells. This triggers an intracellular signaling cascade: cytoplasmic $Ca^{2+}$ rises, activating anion channels and outward rectifying $K^+$ channels ($K^+_{\\text{out}}$). The massive efflux of $K^+$ and anions from guard cells causes water to leave osmotically, leading to loss of turgor and rapid closure of the stomatal pore to prevent desiccation.',
    solution: '1. Water stress triggers ABA synthesis.\n2. ABA binds guard cell receptors $\\implies$ ion efflux ($K^+$ and $Cl^-$).\n3. Guard cells lose turgor pressure $\\implies$ stomata close.',
    concepts: ['Abscisic acid stress signaling', 'Stomatal turgor regulation', 'Guard cell ion transport'],
    commonTrap: 'Selecting auxin or cytokinin (which actually promote stomatal opening and cell division).',
    shortcut: 'ABA = Stress hormone = Stomatal closure under drought.',
    hints: ['Which plant hormone is called the "stress hormone"?', 'What hormone triggers ion efflux from guard cells during water deficiency?', 'It is also responsible for seed dormancy.'],
    source: 'CEE 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 35
  },
  {
    id: 'bio-18',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Ecology & Environment',
    topic: 'Ecosystem Dynamics & Ecological Pyramids',
    difficulty: 'hard',
    question: 'Which of the following ecological pyramids is **NEVER inverted** in any natural ecosystem?',
    options: [
      'Pyramid of Energy',
      'Pyramid of Biomass',
      'Pyramid of Numbers',
      'Both Pyramid of Biomass and Pyramid of Energy'
    ],
    correctAnswer: 0,
    explanation: 'The **Pyramid of Energy** is always strictly upright in every ecosystem without exception. According to the Second Law of Thermodynamics and Lindeman 10% law of trophic efficiency, energy is irreversibly lost as respiratory heat at each successive trophic level. Only approximately $10\\%$ of energy is transferred to the next higher level. Energy can never be created or accumulated in greater amounts in higher trophic levels than is supplied by primary producers. In contrast, the pyramid of biomass can be inverted in aquatic ecosystems (phytoplankton vs zooplankton), and the pyramid of numbers can be inverted in single-tree ecosystems with parasites.',
    solution: '1. Second Law of Thermodynamics dictates continuous loss of usable energy as heat.\n2. Only ~10% transfers to higher trophic levels.\n3. Pyramid of energy is strictly upright and never inverted.',
    concepts: ['Second law of thermodynamics in ecology', 'Lindeman 10% trophic efficiency rule', 'Ecological pyramids'],
    commonTrap: 'Thinking biomass is never inverted. In marine/aquatic ecosystems, the pyramid of biomass is often inverted (tiny phytoplankton standing crop supporting larger zooplankton biomass).',
    shortcut: 'Pyramid of energy is ALWAYS upright. Always.',
    hints: ['Can energy transfer between trophic levels ever exceed 100%?', 'Think about heat loss at each successive step.', 'Which pyramid represents energy flow over time rather than instantaneous standing crop?'],
    source: 'MECEE-BL 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 35
  },
  {
    id: 'bio-19',
    sourceType: 'ai_variation',
    subject: 'Biology',
    chapter: 'Ecology & Environment',
    topic: 'Ecosystem Dynamics & Ecological Pyramids',
    difficulty: 'very_hard',
    question: 'In a marine pelagic ecosystem, why is the **pyramid of biomass inverted** (biomass of zooplankton exceeds biomass of phytoplankton at any given instant) while the system remains ecologically stable?',
    options: [
      'Phytoplankton have extremely high turnover rates and rapid reproductive fecundity, sustaining a larger standing biomass of long-lived zooplankton',
      'Zooplankton do not consume phytoplankton',
      'Primary producers perform anaerobic chemosynthesis',
      'The law of conservation of energy does not apply to marine ecosystems'
    ],
    correctAnswer: 0,
    explanation: 'An inverted pyramid of biomass occurs in open oceans because phytoplankton have a very short lifespan (a few days) and divide extremely rapidly. Their standing crop biomass at any single moment is small, but their production-to-biomass ($P/B$) ratio is enormous. Zooplankton, being larger and longer-lived, consume phytoplankton rapidly and accumulate biomass over a longer period. Thus, a small, rapidly turning-over biomass of primary producers generates sufficient total energy over time to support a larger standing biomass of primary consumers.',
    solution: '1. Standing crop biomass is small for phytoplankton.\n2. Turnover rate (production per unit time) is extraordinarily high.\n3. Over time, total energy produced is much greater, keeping energy pyramid upright even when instantaneous biomass is inverted.',
    concepts: ['Turnover rate in aquatic ecosystems', 'Production to biomass (P/B) ratio', 'Inverted pyramid of biomass'],
    commonTrap: 'Assuming an inverted biomass pyramid violates thermodynamics. Thermodynamics governs energy flow over time, not static instantaneous weight.',
    shortcut: 'Short-lived phytoplankton with rapid turnover support longer-lived zooplankton standing crop.',
    hints: ['How fast do microscopic algae reproduce compared to zooplankton?', 'Does standing crop biomass equal total energy production over time?', 'Think about turnover rates and lifespan differences.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'bio-20',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Genetics & Molecular Biology',
    topic: 'Molecular Genetics: Replication, Transcription, Translation',
    difficulty: 'hard',
    question: 'During protein translation in eukaryotes, the **initiator tRNA** carrying Methionine enters which site of the ribosome, whereas all subsequent aminoacyl-tRNAs enter which site?',
    options: [
      'Initiator tRNA enters the P-site; subsequent tRNAs enter the A-site',
      'Initiator tRNA enters the A-site; subsequent tRNAs enter the P-site',
      'All tRNAs enter exclusively through the A-site',
      'Initiator tRNA enters the E-site; subsequent tRNAs enter the P-site'
    ],
    correctAnswer: 0,
    explanation: 'The ribosome contains three tRNA binding sites: A (aminoacyl), P (peptidyl), and E (exit). During translation initiation, the eukaryotic initiation factor-2 ($e\\text{IF2}$) complex delivers the initiator $\\text{Met-tRNA}_i^{\\text{Met}}$ directly into the **P-site** (peptidyl site) aligned with the start codon $\\text{AUG}$ on mRNA. This is the ONLY tRNA that can bind directly to the P-site. All subsequent incoming aminoacyl-tRNAs during the elongation phase must enter the **A-site** (aminoacyl site), guided by elongation factors ($e\\text{EF1A}$).',
    solution: '1. Initiator Met-tRNA binds directly to the P-site (Peptidyl site).\n2. Elongation tRNAs bind to the A-site (Aminoacyl site).\n3. Peptidyl transferase forms peptide bond from P-site to A-site.',
    concepts: ['Ribosomal A, P, E sites', 'Translation initiation mechanism', 'Initiator tRNA specificity'],
    commonTrap: 'Thinking all tRNAs enter through the A site. The initiator tRNA is the sole exception that enters directly at the P site!',
    shortcut: 'Initiator tRNA goes directly into P site. All other tRNAs enter A site.',
    hints: ['Recall the 3 ribosomal sites: A, P, and E.', 'Which site holds the growing peptide chain?', 'Is the initiator tRNA an exception to the standard entry site?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'bio-21',
    sourceType: 'verified_past',
    subject: 'Biology',
    chapter: 'Human Physiology',
    topic: 'Endocrine System & Hormonal Control',
    difficulty: 'hard',
    question: 'Which of the following hormones acts via an **intracellular nuclear receptor** directly modulating gene transcription, rather than utilizing cell-surface receptors and second messengers ($c\\text{AMP}$ or $IP_3/\\text{DAG}$)?',
    options: [
      'Thyroxine ($T_4$) and Cortisol',
      'Insulin and Glucagon',
      'Adrenaline and Noradrenaline',
      'Oxytocin and Vasopressin'
    ],
    correctAnswer: 0,
    explanation: 'Steroid hormones (e.g. cortisol, aldosterone, estrogen) and iodothyronines (thyroxine $T_4$, triiodothyronine $T_3$) are lipid-soluble lipophilic molecules that readily diffuse across the plasma membrane lipid bilayer. Inside the target cell, they bind to intracellular nuclear receptors. The hormone-receptor complex acts as a ligand-activated transcription factor that binds directly to Hormone Response Elements (HRE) on genomic DNA to regulate gene expression. In contrast, peptide/protein hormones (insulin, glucagon, oxytocin) and catecholamines (adrenaline) are hydrophilic and bind cell surface receptors triggering second messenger cascades.',
    solution: '1. Steroids and thyroid hormones are lipophilic.\n2. They cross membranes and bind intracellular/nuclear receptors to alter transcription.\n3. Peptide hormones and catecholamines bind surface receptors with second messengers.',
    concepts: ['Lipophilic vs hydrophilic hormone mechanisms', 'Nuclear receptor superfamily', 'Hormone response elements (HRE)'],
    commonTrap: 'Thinking thyroxine is a peptide hormone that binds surface receptors because it is derived from tyrosine. Thyroid hormones are lipophilic and bind intracellular nuclear receptors!',
    shortcut: 'Steroids + Thyroid hormones = Intracellular nuclear receptors (gene expression). All peptides/amines = Surface receptors.',
    hints: ['Which hormones can diffuse directly across the hydrophobic plasma membrane?', 'Do thyroid hormones and steroid hormones share intracellular receptors?', 'Insulin, glucagon, and adrenaline cannot enter the cell directly.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  }
];
