import { Question } from '@/types';

export const CHEMISTRY_QUESTIONS: Question[] = [
  {
    id: 'chem-01',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Reaction Mechanisms (SN1, SN2, E1, E2)',
    difficulty: 'hard',
    question: 'Optically active $(R)$-2-bromobutane is treated with sodium iodide ($\\text{NaI}$) in dry acetone. The reaction follows second-order kinetics. The stereochemical outcome and mechanism of the major product are:',
    options: [
      'Inversion of configuration giving $(S)$-2-iodobutane via $S_N2$',
      'Retention of configuration via $S_N1$',
      'Complete racemization via planar carbocation',
      'Predominant elimination giving trans-2-butene via $E2$'
    ],
    correctAnswer: 0,
    explanation: 'Sodium iodide in dry acetone provides iodide ion ($I^-$) in a polar aprotic solvent (Finkelstein reaction condition), which strongly favors $S_N2$. Because $S_N2$ proceeds via backside nucleophilic attack with a concerted transition state, it causes complete inversion of configuration (Walden inversion). The starting $(R)$-2-bromobutane is cleanly inverted to $(S)$-2-iodobutane.',
    solution: '1. Reagents: NaI in dry acetone (polar aprotic).\n2. Second-order kinetics implies $S_N2$ rate law: Rate $= k [\\text{Substrate}][I^-]$.\n3. Backside attack forces 100% Walden inversion at the chiral center: $(R) \\to (S)$.',
    concepts: ['Finkelstein reaction', 'Walden inversion', 'SN2 stereospecificity'],
    commonTrap: 'Assuming secondary halides always produce racemic mixtures.',
    shortcut: 'NaI in acetone + secondary halide = pure SN2 Walden inversion (R -> S).',
    hints: ['Identify the solvent: dry acetone is polar aprotic.', 'What mechanism produces second-order kinetics?', 'What is the stereochemical signature of a backside displacement?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'chem-02',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Reaction Mechanisms (SN1, SN2, E1, E2)',
    difficulty: 'very_hard',
    originalPastQuestionId: 'chem-01',
    question: '$(2R, 3S)$-3-bromo-2-butanol is treated with dilute aqueous $\\text{NaOH}$ at room temperature. An intramolecular nucleophilic substitution occurs forming an epoxide (2,3-dimethyloxirane). What is the stereochemical nature of the resulting epoxide?',
    options: [
      '$(2R, 3R)$-epoxide (meso, optically inactive)',
      '$(2R, 3S)$-epoxide (chiral, optically active)',
      'A $1:1$ racemic mixture of enantiomers',
      '$(2S, 3S)$-epoxide (chiral, optically active)'
    ],
    correctAnswer: 0,
    explanation: 'Basic deprotonation of the C2 hydroxyl group generates an internal alkoxide nucleophile ($C_2-O^-$). For intramolecular $S_N2$ backside displacement of the leaving group $Br^-$ at C3, the alkoxide attacks anti-periplanar. This causes inversion of configuration ONLY at C3, while the chiral center at C2 undergoes no bond breaking and retains its configuration. The starting $(2R, 3S)$ configuration with inverted C3 yields a molecule with an internal mirror plane of symmetry (meso-2,3-dimethyloxirane), which is optically inactive.',
    solution: '1. Intramolecular SN2 epoxide formation.\n2. Inversion occurs exclusively at C3 (the carbon bearing the leaving group Br).\n3. C2 retains configuration (no bond cleavage at C2).\n4. Inversion at C3 transforms the diastereomer into the symmetric meso stereoisomer.',
    concepts: ['Intramolecular SN2', 'Anti-periplanar geometry', 'Meso compounds'],
    commonTrap: 'Believing both chiral centers invert. Only the carbon where substitution occurs inverts.',
    shortcut: 'Intramolecular attack on adjacent halo-alcohol inverts only one center $\\implies$ (2R, 3S) converts to the symmetric meso epoxide.',
    hints: ['Which atom acts as the nucleophile after deprotonation?', 'Does the carbon with the OH group undergo bond cleavage?', 'Look at the symmetry of the resulting 2,3-dimethyloxirane.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 85
  },
  {
    id: 'chem-03',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Ionic Equilibrium & Buffers',
    difficulty: 'hard',
    question: 'The solubility product of $\\text{Ag}_2\\text{CrO}_4$ is $3.2 \\times 10^{-11}$ and that of $\\text{AgCl}$ is $1.8 \\times 10^{-10}$ at $25^\\circ\\text{C}$. To a solution containing $0.1\\,\\text{M}$ each of $\\text{Cl}^-$ and $\\text{CrO}_4^{2-}$, $\\text{AgNO}_3$ is added dropwise. Which salt precipitates first, and what is $[\\text{Ag}^+]$ required for the second precipitate to appear?',
    options: [
      '$\\text{AgCl}$ precipitates first; $[\\text{Ag}^+] = 1.79 \\times 10^{-5}\\,\\text{M}$',
      '$\\text{Ag}_2\\text{CrO}_4$ precipitates first; $[\\text{Ag}^+] = 1.8 \\times 10^{-9}\\,\\text{M}$',
      '$\\text{AgCl}$ precipitates first; $[\\text{Ag}^+] = 3.2 \\times 10^{-10}\\,\\text{M}$',
      'Both precipitate simultaneously'
    ],
    correctAnswer: 0,
    explanation: 'For $\\text{AgCl}$: $[\\text{Ag}^+] = K_{sp} / [\\text{Cl}^-] = 1.8 \\times 10^{-10} / 0.1 = 1.8 \\times 10^{-9}\\,\\text{M}$. For $\\text{Ag}_2\\text{CrO}_4$: $[\\text{Ag}^+] = \\sqrt{K_{sp} / [\\text{CrO}_4^{2-}]} = \\sqrt{3.2 \\times 10^{-11} / 0.1} = \\sqrt{3.2 \\times 10^{-10}} \\approx 1.79 \\times 10^{-5}\\,\\text{M}$. Since $1.8 \\times 10^{-9}\\,\\text{M} < 1.79 \\times 10^{-5}\\,\\text{M}$, $\\text{AgCl}$ precipitates first. The second precipitate appears when $[\\text{Ag}^+]$ reaches $1.79 \\times 10^{-5}\\,\\text{M}$.',
    solution: '1. AgCl threshold: $[Ag^+] = 1.8 \\times 10^{-10} / 0.1 = 1.8 \\times 10^{-9}\\,M$.\n2. $Ag_2CrO_4$ threshold: $[Ag^+] = \\sqrt{3.2 \\times 10^{-11} / 0.1} = 1.79 \\times 10^{-5}\\,M$.\n3. Lower concentration precipitates first (AgCl).\n4. Second salt begins at $1.79 \\times 10^{-5}\\,M$.',
    concepts: ['Fractional precipitation', 'Solubility product comparison', 'Common ion effect'],
    commonTrap: 'Comparing numerical $K_{sp}$ values directly without computing $[Ag^+]$ for different stoichiometry types (AB vs A2B).',
    shortcut: 'Never compare Ksp directly between different salt stoichiometries! Compute required cation concentration.',
    hints: ['Do not compare $K_{sp}$ directly because one is $AB$ and the other is $A_2B$.', 'Calculate the minimum $[\\text{Ag}^+]$ required to precipitate each salt.', 'The salt that requires the lower concentration precipitates first.'],
    source: 'MECEE-BL 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'chem-04',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Chemical Kinetics',
    difficulty: 'hard',
    question: 'For a first-order reaction $A \\to \\text{Products}$, the time required for $75\\%$ completion is $t_1$ and for $99.9\\%$ completion is $t_2$. The ratio $t_2 / t_1$ is approximately:',
    options: [
      '$5$',
      '$10$',
      '$2.5$',
      '$3.3$'
    ],
    correctAnswer: 0,
    explanation: 'For a first-order reaction: (1) $75\\%$ completion means $25\\% = 1/4 = (1/2)^2$ of the reactant remains, which corresponds to exactly $2$ half-lives ($t_1 = 2 T_{1/2}$). (2) $99.9\\%$ completion means $0.1\\% = 1/1000 \\approx 1/1024 = (1/2)^{10}$ of the reactant remains, which corresponds to $10$ half-lives ($t_2 = 10 T_{1/2}$). Therefore, the ratio $t_2 / t_1 = 10 / 2 = 5$.',
    solution: '1. $t_{75\\%} = 2 \\times t_{1/2}$.\n2. $t_{99.9\\%} = \\frac{2.303}{k} \\log(100/0.1) = \\frac{2.303 \\times 3}{k} \\approx 10 \\times t_{1/2}$.\n3. Ratio $t_2 / t_1 = 10 / 2 = 5$.',
    concepts: ['First-order integrated rate law', 'Half-life properties', 'Logarithmic completion times'],
    commonTrap: 'Trying to use proportionality of percentages: $99.9 / 75 = 1.33$ (invalid for first-order exponential decay).',
    shortcut: '$t_{99.9\\%} = 10 t_{1/2}$ and $t_{75\\%} = 2 t_{1/2} \\implies$ Ratio is $10/2 = 5$.',
    hints: ['Express both times in terms of half-life $t_{1/2}$.', 'How many half-lives correspond to $75\\%$ decay?', 'Recall the standard CEE identity: $t_{99.9\\%} = 10 t_{1/2}$.'],
    source: 'CEE 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'chem-05',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'Coordination Compounds',
    difficulty: 'hard',
    question: 'Which of the following complex ions is **diamagnetic** and involves $dsp^2$ hybridization of the central metal ion?',
    options: [
      '$[\\text{Ni(CN)}_4]^{2-}$',
      '$[\\text{NiCl}_4]^{2-}$',
      '$[\\text{CoF}_6]^{3-}$',
      '$[\\text{Fe(CN)}_6]^{3-}$'
    ],
    correctAnswer: 0,
    explanation: 'In $[\\text{Ni(CN)}_4]^{2-}$, the central metal is $Ni^{2+}$ ($d^8$ configuration: $[Ar] 3d^8$). Cyanide ($CN^-$) is a strong field ligand in the spectrochemical series and forces pairing of the two unpaired $3d$ electrons into four $3d$ orbitals. This leaves one vacant $3d$ orbital, one $4s$, and two $4p$ orbitals, undergoing $dsp^2$ hybridization with square planar geometry. With zero unpaired electrons, it is diamagnetic. In contrast, $[\\text{NiCl}_4]^{2-}$ has weak field $Cl^-$ (tetrahedral $sp^3$, paramagnetic).',
    solution: '1. $Ni^{2+}$: $3d^8 4s^0$.\n2. $CN^-$ is strong field ligand $\\implies$ electrons pair up in $3d$: $(2,2,2,2,0)$.\n3. Vacant orbitals used: one $3d$, one $4s$, two $4p \\implies dsp^2$ square planar.\n4. Zero unpaired electrons $\\implies$ diamagnetic.',
    concepts: ['Crystal field theory', 'Strong vs weak field ligands', 'dsp2 hybridization & magnetic moment'],
    commonTrap: 'Thinking all 4-coordinate complexes are tetrahedral $sp^3$. Strong field ligands with $d^8$ metals form square planar $dsp^2$.',
    shortcut: 'Ni(II) with CN- = d8 strong field = square planar dsp2 = diamagnetic.',
    hints: ['Find the oxidation state and d-electron count of Ni.', 'Is CN- a weak field or strong field ligand?', 'Does pairing of 8 electrons leave a vacant d orbital?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'chem-06',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'Coordination Compounds',
    difficulty: 'very_hard',
    question: 'The Crystal Field Stabilization Energy (CFSE) for high-spin and low-spin $d^6$ octahedral complexes (ignoring pairing energy $P$) are, respectively:',
    options: [
      '$-0.4\\,\\Delta_o$ and $-2.4\\,\\Delta_o$',
      '$-0.6\\,\\Delta_o$ and $-1.8\\,\\Delta_o$',
      '$-0.4\\,\\Delta_o$ and $-1.6\\,\\Delta_o$',
      '$-1.2\\,\\Delta_o$ and $-2.4\\,\\Delta_o$'
    ],
    correctAnswer: 0,
    explanation: 'In an octahedral field, $d$-orbitals split into $t_{2g}$ (energy $-0.4\\Delta_o$) and $e_g$ (energy $+0.6\\Delta_o$). For high-spin $d^6$: configuration is $t_{2g}^4 e_g^2$. CFSE $= 4(-0.4\\Delta_o) + 2(+0.6\\Delta_o) = -1.6\\Delta_o + 1.2\\Delta_o = -0.4\\,\\Delta_o$. For low-spin $d^6$: configuration is $t_{2g}^6 e_g^0$. CFSE $= 6(-0.4\\Delta_o) + 0 = -2.4\\,\\Delta_o$.',
    solution: '1. High-spin $d^6$: $t_{2g}^4 e_g^2 \\implies \\text{CFSE} = 4(-0.4) + 2(0.6) = -0.4\\,\\Delta_o$.\n2. Low-spin $d^6$: $t_{2g}^6 e_g^0 \\implies \\text{CFSE} = 6(-0.4) = -2.4\\,\\Delta_o$.',
    concepts: ['Octahedral splitting $\\Delta_o$', 't2g and eg energy levels', 'High-spin vs low-spin CFSE'],
    commonTrap: 'Mixing up octahedral $-0.4/+0.6$ splitting with tetrahedral $-0.6/+0.4$ splitting.',
    shortcut: 'Low-spin d6 has all 6 electrons in t2g: $6 \\times (-0.4) = -2.4\\Delta_o$. High-spin: $4(-0.4) + 2(0.6) = -0.4\\Delta_o$.',
    hints: ['Recall the energies of $t_{2g}$ ($-0.4\\Delta_o$) and $e_g$ ($+0.6\\Delta_o$).', 'Write electron distribution for high-spin $d^6$ ($t_{2g}^4 e_g^2$).', 'Write electron distribution for low-spin $d^6$ ($t_{2g}^6 e_g^0$).'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'chem-07',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Aldehydes, Ketones & Carboxylic Acids',
    difficulty: 'hard',
    question: 'A carbonyl compound $X$ on treatment with hydrazine ($\\text{NH}_2\\text{NH}_2$) followed by heating with $\\text{KOH}$ in ethylene glycol yields $n$-butane. Compound $X$ also gives a positive yellow precipitate with $\\text{I}_2/\\text{NaOH}$ (haloform test). The structural formula of $X$ is:',
    options: [
      '$\\text{CH}_3\\text{COCH}_2\\text{CH}_3$ (2-butanone)',
      '$\\text{CH}_3\\text{CH}_2\\text{CH}_2\\text{CHO}$ (butanal)',
      '$\\text{CH}_3\\text{COCH}_3$ (propanone)',
      '$\\text{CH}_3\\text{CH}_2\\text{COCH}_2\\text{CH}_3$ (3-pentanone)'
    ],
    correctAnswer: 0,
    explanation: '1. Reduction with $\\text{NH}_2\\text{NH}_2 / \\text{KOH} / \\text{glycol}$ is the Wolff-Kishner reduction, which converts a $C=O$ group into a $-CH_2-$ group without altering the carbon chain length. Since the product is $n$-butane (4 carbons), compound $X$ must be a 4-carbon carbonyl compound. 2. A positive haloform test (yellow precipitate of $\\text{CHI}_3$) requires a methyl carbonyl group ($\\text{CH}_3-C=O$). Only 2-butanone ($\\text{CH}_3\\text{COCH}_2\\text{CH}_3$) has 4 carbons and contains the required $\\text{CH}_3-C=O$ group (butanal lacks a methyl ketone group).',
    solution: '1. Wolff-Kishner gives n-butane (4 carbons) $\\implies X$ has 4 carbons.\n2. Positive iodoform test $\\implies$ contains $CH_3-C=O$ group.\n3. 4 carbons + methyl ketone = 2-butanone ($CH_3COCH_2CH_3$).',
    concepts: ['Wolff-Kishner reduction', 'Iodoform test requirement', 'Carbonyl functional group identification'],
    commonTrap: 'Picking butanal because it is a straight chain aldehyde; aldehydes other than acetaldehyde do NOT give a positive haloform test.',
    shortcut: '4 carbons + positive iodoform = 2-butanone.',
    hints: ['What reduction uses hydrazine and KOH in ethylene glycol?', 'What functional group is required for a positive yellow iodoform precipitate?', 'Combine carbon count (4) with the methyl carbonyl requirement.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'chem-08',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Aldehydes, Ketones & Carboxylic Acids',
    difficulty: 'very_hard',
    question: 'When benzaldehyde is treated with concentrated aqueous $\\text{NaOH}$ (Cannizzaro reaction), the reaction is fourth-order overall (second-order in benzaldehyde and second-order in hydroxide ion at high base concentration). The rate-determining step in this mechanism is:',
    options: [
      'Hydride ion ($H^-$) transfer from the dianion intermediate to another benzaldehyde molecule',
      'Nucleophilic attack of $OH^-$ on the carbonyl carbon of benzaldehyde',
      'Deprotonation of benzoic acid by sodium hydroxide',
      'Proton transfer between benzyl alcohol and benzoate ion'
    ],
    correctAnswer: 0,
    explanation: 'In the Cannizzaro reaction of non-enolizable aldehydes, $OH^-$ attacks the carbonyl carbon to form a monoanion, which at high base concentration is further deprotonated to a dianion $[\\text{PhCH}(O^-)_2]$. The rate-determining slow step is the direct transfer of a hydride ion ($H^-$) from this electron-rich dianion intermediate to the carbonyl carbon of a second benzaldehyde molecule.',
    solution: '1. Step 1 (fast eq): $\\text{PhCHO} + OH^- \\rightleftharpoons \\text{PhCH(OH)}O^-$.\n2. Step 2 (fast eq): $\\text{PhCH(OH)}O^- + OH^- \\rightleftharpoons \\text{PhCH}(O^-)_2 + H_2O$.\n3. Step 3 (slow rate-determining): Hydride ($H^-$) transfer from dianion to second PhCHO molecule.',
    concepts: ['Cannizzaro reaction mechanism', 'Hydride transfer step', 'Reaction order in organic mechanisms'],
    commonTrap: 'Assuming the initial nucleophilic attack of hydroxide is the rate-determining step.',
    shortcut: 'In Cannizzaro, hydride ($H^-$) transfer is always the slowest (rate-determining) step.',
    hints: ['Recall which species is transferred between the two aldehyde molecules.', 'Hydride ($H^-$) is a poor leaving group and difficult to transfer.', 'The transfer of hydride from the adduct to the second aldehyde is rate-limiting.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 65
  },
  {
    id: 'chem-09',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Electrochemistry & Nernst Equation',
    difficulty: 'hard',
    question: 'For the cell: $\\text{Zn}(s) | \\text{Zn}^{2+}(0.01\\,\\text{M}) \\parallel \\text{Cu}^{2+}(0.1\\,\\text{M}) | \\text{Cu}(s)$, the standard cell potential $E^\\circ_{\\text{cell}} = 1.10\\,\\text{V}$. The EMF of the cell at $298\\,\\text{K}$ is (take $\\frac{2.303 R T}{F} = 0.0591\\,\\text{V}$):',
    options: [
      '$1.1295\\,\\text{V}$',
      '$1.0705\\,\\text{V}$',
      '$1.1591\\,\\text{V}$',
      '$1.0409\\,\\text{V}$'
    ],
    correctAnswer: 0,
    explanation: 'Cell reaction: $\\text{Zn}(s) + \\text{Cu}^{2+}(aq) \\rightleftharpoons \\text{Zn}^{2+}(aq) + \\text{Cu}(s)$, with $n = 2$. Reaction quotient $Q = \\frac{[\\text{Zn}^{2+}]}{[\\text{Cu}^{2+}]} = \\frac{0.01}{0.1} = 0.1 = 10^{-1}$. By Nernst equation: $E_{\\text{cell}} = E^\\circ_{\\text{cell}} - \\frac{0.0591}{n} \\log Q = 1.10 - \\frac{0.0591}{2} \\log(10^{-1}) = 1.10 - (-0.02955) = 1.10 + 0.02955 = 1.12955\\,\\text{V} \\approx 1.1295\\,\\text{V}$.',
    solution: '1. $n = 2$ electrons transferred.\n2. $Q = [Zn^{2+}]/[Cu^{2+}] = 0.01 / 0.1 = 10^{-1}$.\n3. $\\log Q = -1$.\n4. $E = 1.10 - (0.0591 / 2)(-1) = 1.10 + 0.02955 = 1.1295\\,\\text{V}$.',
    concepts: ['Nernst equation at 298 K', 'Reaction quotient Q in galvanic cells', 'Concentration dependence of EMF'],
    commonTrap: 'Subtracting $0.0295$ instead of adding it when $\\log Q < 0$.',
    shortcut: '$[Cu^{2+}] > [Zn^{2+}] \\implies$ Le Chatelier favors forward reaction $\\implies E > E^\\circ$. Only option A ($1.1295\\,\\text{V}$) is $> 1.10\\,\\text{V}$.',
    hints: ['Identify the number of electrons transferred ($n = 2$).', 'Calculate reaction quotient $Q = [\\text{Zn}^{2+}] / [\\text{Cu}^{2+}]$.', 'Notice $\\log(0.1) = -1$, which changes the subtraction to an addition.'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'chem-10',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'Chemical Bonding & Molecular Structure',
    difficulty: 'hard',
    question: 'According to Molecular Orbital Theory (MOT), which of the following diatomic species is **paramagnetic** and has a bond order of $2.5$?',
    options: [
      '$\\text{NO}$',
      '$\\text{CO}$',
      '$\\text{O}_2^+$',
      'Both $\\text{NO}$ and $\\text{O}_2^+$'
    ],
    correctAnswer: 3,
    explanation: 'Total valence/valence electrons: (1) $\\text{NO}$ has $7 + 8 = 15$ electrons. Bond order $= \\frac{10 - 5}{2} = 2.5$. It has 1 unpaired electron in $\\pi^* 2p$, so it is paramagnetic. (2) $\\text{O}_2^+$ has $8 + 8 - 1 = 15$ electrons. Isoelectronic with $\\text{NO}$, its bond order is also $2.5$ with 1 unpaired electron (paramagnetic). (3) $\\text{CO}$ has $6 + 8 = 14$ electrons, bond order $= 3$, diamagnetic. Therefore, BOTH $\\text{NO}$ and $\\text{O}_2^+$ qualify!',
    solution: '1. NO has 15 electrons: $\\text{BO} = (10 - 5)/2 = 2.5$, 1 unpaired electron $\\implies$ paramagnetic.\n2. $O_2^+$ has 15 electrons: $\\text{BO} = (10 - 5)/2 = 2.5$, 1 unpaired electron $\\implies$ paramagnetic.\n3. Both satisfy the conditions.',
    concepts: ['Molecular orbital electronic configurations', 'Bond order formula', 'Isoelectronic species'],
    commonTrap: 'Picking only NO and forgetting that $O_2^+$ has the exact same 15-electron configuration.',
    shortcut: '15 electrons always has Bond Order = 2.5 and is paramagnetic (1 unpaired electron). NO and O2+ both have 15 electrons.',
    hints: ['Count total electrons for each species.', 'What is the bond order for 15 electrons?', 'Any species with an odd total number of electrons must have an unpaired electron (paramagnetic).'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'chem-11',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'Chemical Bonding & Molecular Structure',
    difficulty: 'elite',
    question: 'The species with the **highest bond dissociation energy** among the following is:',
    options: [
      '$\\text{CO}$',
      '$\\text{N}_2$',
      '$\\text{NO}^+$',
      '$\\text{O}_2^{2-}$'
    ],
    correctAnswer: 0,
    explanation: 'Both $\\text{CO}$, $\\text{N}_2$, and $\\text{NO}^+$ are 14-electron species with a bond order of $3$. However, $\\text{CO}$ possesses significant polar character with a strong triple bond ($1072\\,\\text{kJ/mol}$) compared to $\\text{N}_2$ ($945\\,\\text{kJ/mol}$). The partial ionic character and back-bonding in carbon monoxide make the $C \\equiv O$ bond the strongest known chemical bond in neutral diatomic molecules.',
    solution: '1. All three (CO, N2, NO+) have bond order 3.0.\n2. CO bond dissociation enthalpy is $1072\\,\\text{kJ/mol}$ due to electronegativity difference and triple bond stabilization.\n3. N2 bond dissociation enthalpy is $945\\,\\text{kJ/mol}$.\n4. CO has the highest bond dissociation energy.',
    concepts: ['Bond dissociation energy', 'Isoelectronic bond strength comparison', 'Ionic contribution to covalent triple bonds'],
    commonTrap: 'Assuming N2 has the strongest bond because of its inertness. CO actually has a higher bond energy ($1072\\,\\text{kJ/mol}$ vs $945\\,\\text{kJ/mol}$).',
    shortcut: 'CO has the highest bond dissociation energy among all neutral diatomic molecules ($1072\\,\\text{kJ/mol}$).',
    hints: ['All three have bond order 3.', 'Does bond polarity add extra electrostatic stability to the covalent bond?', 'CO has a higher dissociation enthalpy than N2.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'chem-12',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Amines & Diazonium Salts',
    difficulty: 'hard',
    question: 'The correct order of basic strength of methyl-substituted amines in **aqueous solution** is:',
    options: [
      '$(\\text{CH}_3)_2\\text{NH} > \\text{CH}_3\\text{NH}_2 > (\\text{CH}_3)_3\\text{N} > \\text{NH}_3$',
      '$(\\text{CH}_3)_3\\text{N} > (\\text{CH}_3)_2\\text{NH} > \\text{CH}_3\\text{NH}_2 > \\text{NH}_3$',
      '$(\\text{CH}_3)_2\\text{NH} > (\\text{CH}_3)_3\\text{N} > \\text{CH}_3\\text{NH}_2 > \\text{NH}_3$',
      '$\\text{CH}_3\\text{NH}_2 > (\\text{CH}_3)_2\\text{NH} > (\\text{CH}_3)_3\\text{N} > \\text{NH}_3$'
    ],
    correctAnswer: 0,
    explanation: 'In aqueous medium, basicity is governed by an interplay of: (1) Inductive effect ($+I$), (2) Solvation effect (hydrogen bonding of conjugate acid with water), and (3) Steric hindrance. For methyl group substituents, the balance of these effects gives the order: $2^\\circ > 1^\\circ > 3^\\circ > \\text{NH}_3$ (i.e. $(\\text{CH}_3)_2\\text{NH} > \\text{CH}_3\\text{NH}_2 > (\\text{CH}_3)_3\\text{N} > \\text{NH}_3$). For ethyl groups, steric hindrance shifts the order to $2^\\circ > 3^\\circ > 1^\\circ > \\text{NH}_3$.',
    solution: '1. In gas phase: $3^\\circ > 2^\\circ > 1^\\circ > \\text{NH}_3$.\n2. In aqueous solution with methyl group: $2^\\circ > 1^\\circ > 3^\\circ > \\text{NH}_3$ (213 order).\n3. With ethyl group: $2^\\circ > 3^\\circ > 1^\\circ > \\text{NH}_3$ (231 order).',
    concepts: ['Amine basicity in aqueous medium', 'Solvation energy of ammonium cations', 'Steric vs inductive interplay'],
    commonTrap: 'Applying the gas-phase $+I$ order ($3 > 2 > 1$) to aqueous solution where hydration and steric factors invert tertiary amine basicity.',
    shortcut: 'Methyl amines in water: "213" order. Ethyl amines in water: "231" order.',
    hints: ['Recall that hydration and steric hindrance modify inductive effects in water.', 'Remember the mnemonic rule for methyl vs ethyl in water.', 'For methyl, secondary is first, followed by primary, then tertiary.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'chem-13',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Ionic Equilibrium & Buffers',
    difficulty: 'hard',
    question: 'A buffer solution contains $0.2\\,\\text{M}$ acetic acid ($\\text{CH}_3\\text{COOH}$, $K_a = 1.8 \\times 10^{-5}$) and $0.2\\,\\text{M}$ sodium acetate ($\\text{CH}_3\\text{COONa}$). What is the pH change when $0.01\\,\\text{mol}$ of solid $\\text{NaOH}$ is added to $1.0\\,\\text{L}$ of this buffer solution?',
    options: [
      'Increases by $0.044$',
      'Decreases by $0.044$',
      'Increases by $0.44$',
      'Remains exactly unchanged'
    ],
    correctAnswer: 0,
    explanation: 'Initial pH: by Henderson-Hasselbalch equation, $\\text{pH}_1 = pK_a + \\log\\frac{[\\text{Salt}]}{[\\text{Acid}]} = pK_a + \\log\\frac{0.2}{0.2} = pK_a = -\\log(1.8 \\times 10^{-5}) = 4.745$. When $0.01\\,\\text{mol}$ $\\text{NaOH}$ is added, it reacts with acetic acid: new $[\\text{Acid}] = 0.20 - 0.01 = 0.19\\,\\text{M}$; new $[\\text{Salt}] = 0.20 + 0.01 = 0.21\\,\\text{M}$. New pH: $\\text{pH}_2 = pK_a + \\log\\frac{0.21}{0.19} = 4.745 + \\log(1.105) = 4.745 + 0.0435 = 4.789$. Change in pH: $\\Delta\\text{pH} = +0.044$ (increases slightly).',
    solution: '1. Initial pH $= pK_a = 4.745$.\n2. Addition of base converts acid to conjugate base: $[\text{Acid}] = 0.19$, $[\text{Salt}] = 0.21$.\n3. $\\Delta\\text{pH} = \\log(0.21 / 0.19) = \\log(1.105) \\approx +0.044$.',
    concepts: ['Henderson-Hasselbalch equation', 'Buffer capacity', 'Stoichiometry of buffer neutralization'],
    commonTrap: 'Thinking an ideal buffer has $\\Delta\\text{pH} = 0.000$. A buffer resists pH changes, but small additions still cause slight quantifiable shifts.',
    shortcut: '$\\Delta\\text{pH} = \\log\\frac{0.20 + 0.01}{0.20 - 0.01} = \\log(21/19) \\approx +0.044$.',
    hints: ['Calculate initial pH using $[\\text{Salt}] / [\\text{Acid}] = 1$.', 'Account for consumption of acid and formation of salt upon adding $\\text{NaOH}$.', 'Use $\\log(21/19)$ to find the change.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'chem-14',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Ionic Equilibrium & Buffers',
    difficulty: 'very_hard',
    question: 'The pH of a $1.0 \\times 10^{-8}\\,\\text{M}$ aqueous solution of hydrochloric acid ($\\text{HCl}$) at $25^\\circ\\text{C}$ is:',
    options: [
      '$6.98$',
      '$8.00$',
      '$7.00$',
      '$6.00$'
    ],
    correctAnswer: 0,
    explanation: 'At extreme dilution ($< 10^{-6}\\,\\text{M}$), auto-ionization of water cannot be neglected. Total $[H^+] = [H^+]_{\\text{HCl}} + [H^+]_{\\text{H}_2\\text{O}} = 10^{-8} + x$. By water self-ionization: $[H^+][OH^-] = (10^{-8} + x)(x) = 1.0 \\times 10^{-14} \\implies x^2 + 10^{-8} x - 10^{-14} = 0$. Solving the quadratic yields $x = 0.95 \\times 10^{-7}\\,\\text{M}$. Total $[H^+] = 1.0 \\times 10^{-8} + 0.95 \\times 10^{-7} = 1.05 \\times 10^{-7}\\,\\text{M}$. $\\text{pH} = -\\log(1.05 \\times 10^{-7}) = 7 - \\log(1.05) = 7 - 0.021 = 6.98$.',
    solution: '1. Total $[H^+] = 10^{-8} + [H^+]_{water}$.\n2. $[H^+]_{water} = [OH^-] = x$.\n3. $(10^{-8} + x)x = 10^{-14} \\implies x = 9.51 \\times 10^{-8}$.\n4. $[H^+]_{total} = 1.051 \\times 10^{-7} \\implies \\text{pH} = 6.98$.',
    concepts: ['Auto-ionization of water', 'Very dilute strong acid pH', 'Quadratic equilibrium equation'],
    commonTrap: 'Blindly calculating $\\text{pH} = -\\log(10^{-8}) = 8$. An acid solution can NEVER be basic ($\\text{pH} > 7$) at $25^\\circ\\text{C}$!',
    shortcut: 'An acid must have $\\text{pH} < 7.0$. At $10^{-8}\\,\\text{M}$, water contribution dominates, pulling pH just below 7 ($6.98$).',
    hints: ['Can an acid solution ever have $\\text{pH} = 8$ at room temperature?', 'Remember to include $[H^+]$ from water auto-ionization ($10^{-7}\\,\\text{M}$).', 'The resulting pH must be slightly less than 7.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'chem-15',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'd- and f-Block Elements & Metallurgy',
    difficulty: 'hard',
    question: 'The atomic and ionic radii of Zirconium ($\\text{Zr}$, atomic number $40$) and Hafnium ($\\text{Hf}$, atomic number $72$) are nearly identical ($160\\,\\text{pm}$ and $159\\,\\text{pm}$). This phenomenon is fundamentally caused by:',
    options: [
      'Lanthanoid contraction due to poor shielding of $4f$ electrons',
      'Actinoid contraction due to $5f$ electrons',
      'Diagonal relationship across groups 4 and 5',
      'Identical nuclear charge and equal number of shells'
    ],
    correctAnswer: 0,
    explanation: 'Between lanthanum ($Z=57$) and hafnium ($Z=72$) lie the 14 lanthanoid elements, in which the $4f$ subshell is sequentially filled. Because $4f$ electrons have diffuse spatial shapes, their mutual shielding of the nuclear charge is extremely poor. As nuclear charge increases by 14 units without proportional shielding, the effective nuclear charge ($Z_{\\text{eff}}$) increases sharply, pulling outer electrons inward. This "Lanthanoid Contraction" precisely cancels the expected increase in size from $4d$ to $5d$ transition series.',
    solution: '1. Zr is in 4d series; Hf is in 5d series.\n2. The 14 lanthanoids precede Hf, filling the 4f subshell.\n3. Poor shielding of 4f electrons causes Lanthanoid Contraction, making Zr and Hf nearly identical in radii.',
    concepts: ['Lanthanoid contraction', '4f shielding inefficiency', 'Effective nuclear charge trends'],
    commonTrap: 'Attributing the similarity to a "diagonal relationship" (which applies only to second and third period light elements like Li/Mg, Be/Al).',
    shortcut: 'Similarity in radii of Zr/Hf, Nb/Ta, Mo/W is the textbook consequence of Lanthanoid Contraction.',
    hints: ['Hf is preceded by the 14 lanthanoids.', 'How effective are $4f$ electrons at shielding nuclear charge?', 'What is the name of the steady contraction across the lanthanoid series?'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'chem-16',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Reaction Mechanisms (SN1, SN2, E1, E2)',
    difficulty: 'hard',
    question: 'When 2-bromo-2-methylbutane is treated with potassium tert-butoxide ($t\\text{-BuOK}$) in tert-butanol, the major elimination product obtained is:',
    options: [
      '2-methyl-1-butene (Hoffmann product)',
      '2-methyl-2-butene (Saytzeff product)',
      '3-methyl-1-butene',
      '2-butanol'
    ],
    correctAnswer: 0,
    explanation: 'Potassium tert-butoxide is a sterically bulky strong base. Due to steric hindrance, it cannot easily access the more substituted, sterically crowded internal $\\beta$-hydrogen to give the thermodynamically more stable Saytzeff alkene. Instead, it abstract the less hindered, more accessible primary $\\beta$-hydrogen from the methyl group, leading predominantly to 2-methyl-1-butene as the major product (Hoffmann elimination product).',
    solution: '1. Base: $t\\text{-BuOK}$ (sterically bulky base).\n2. Bulky base abstracts less hindered terminal $\\beta$-H.\n3. Terminal elimination gives 2-methyl-1-butene (Hoffmann product) as major product.',
    concepts: ['Saytzeff vs Hoffmann elimination', 'Steric bulk of bases', 'E2 regioselectivity'],
    commonTrap: 'Applying Saytzeff rule automatically without considering the steric bulk of potassium tert-butoxide.',
    shortcut: 'Bulky base ($t$-BuOK) = Hoffmann product (least substituted alkene). Small base (EtO-) = Saytzeff product.',
    hints: ['Is potassium tert-butoxide a small or bulky base?', 'Can a bulky base access the hindered internal hydrogen easily?', 'Which alkene is the less substituted Hoffmann product?'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'chem-17',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Reaction Mechanisms (SN1, SN2, E1, E2)',
    difficulty: 'elite',
    question: 'Neopentyl bromide ($(\\text{CH}_3)_3\\text{C-CH}_2\\text{Br}$) is known to be exceptionally unreactive towards $S_N2$ displacement (rate is $10^{-5}$ times that of ethyl bromide). The fundamental reason for this dramatic rate suppression is:',
    options: [
      'Severe steric hindrance in the pentacoordinated $S_N2$ transition state caused by the bulky tert-butyl group',
      'Inability to form a carbocation',
      'High electronegativity of the methyl groups',
      'Steric inhibition of resonance'
    ],
    correctAnswer: 0,
    explanation: 'Although neopentyl bromide is a primary alkyl halide, the carbon adjacent to the reaction center ($\\\\beta$-carbon) bears three bulky methyl groups. In the concerted $S_N2$ transition state, the incoming nucleophile and the leaving group are both partially bonded, requiring a tight pentacoordinated geometry. The three methyl groups create immense steric crowding that destabilizes this transition state, suppressing the reaction rate by a factor of over $100,000$.',
    solution: '1. Primary substrate, but with quaternary $\\beta$-carbon.\n2. In $S_N2$, backside attack requires space for the nucleophile.\n3. The three bulky methyl groups block backside trajectory and heavily crowd the transition state.',
    concepts: ['Steric hindrance at $\\beta$-carbon', 'SN2 transition state crowding', 'Neopentyl effect'],
    commonTrap: 'Thinking primary halides are always fast in SN2. Neopentyl is primary but effectively inert to SN2.',
    shortcut: 'Neopentyl halide = primary halide with tertiary $\\beta$-carbon = massive steric crowding in SN2 transition state.',
    hints: ['Look at the carbon adjacent to the $-CH_2Br$ group.', 'How many methyl groups are attached to the $\\beta$-carbon?', 'Think about the geometry of the $S_N2$ transition state.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'chem-18',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Electrochemistry & Nernst Equation',
    difficulty: 'hard',
    question: 'How many Faradays of electricity are required to reduce $1.0\\,\\text{mol}$ of dichromate ions ($\\text{Cr}_2\\text{O}_7^{2-}$) to $\\text{Cr}^{3+}$ in acidic medium?',
    options: [
      '$6\\,\\text{F}$',
      '$3\\,\\text{F}$',
      '$2\\,\\text{F}$',
      '$12\\,\\text{F}$'
    ],
    correctAnswer: 0,
    explanation: 'The balanced half-reaction in acidic medium is: $\\text{Cr}_2\\text{O}_7^{2-} + 14\\text{H}^+ + 6e^- \\to 2\\text{Cr}^{3+} + 7\\text{H}_2\\text{O}$. Each mole of $\\text{Cr}_2\\text{O}_7^{2-}$ requires $6\\,\\text{moles}$ of electrons for complete reduction (each Cr atom changes oxidation state from $+6$ to $+3$, requiring $3e^-$ per Cr $\\times 2\\,\\text{Cr atoms} = 6e^-$). By Faraday law, $1\\,\\text{mol}$ of electrons corresponds to $1\\,\\text{Faraday}$ ($1\\,\\text{F}$), so $6\\,\\text{Faradays}$ are required.',
    solution: '1. Oxidation state of Cr in $\\text{Cr}_2\\text{O}_7^{2-}$: $2x - 14 = -2 \\implies x = +6$.\n2. Product is $\\text{Cr}^{3+}$: state is $+3$.\n3. Change per Cr $= 3$. For 2 Cr atoms in the formula: $2 \\times 3 = 6$ electrons.\n4. $6\\,\\text{moles of electrons} = 6\\,\\text{Faradays}$.',
    concepts: ['Faraday laws of electrolysis', 'Redox balancing in acidic medium', 'Oxidation number changes'],
    commonTrap: 'Considering only 1 Cr atom ($3\\text{F}$) instead of the diatomic dichromate ion containing 2 Cr atoms ($6\\text{F}$).',
    shortcut: '$\\text{Cr}_2^{+6} \\to 2\\text{Cr}^{+3} \\implies 2 \\times (6 - 3) = 6e^- = 6\\,\\text{F}$.',
    hints: ['Determine the oxidation state of Cr in dichromate.', 'How many Cr atoms are present in one formula unit of dichromate?', 'Multiply the oxidation state change per atom by the number of Cr atoms.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'chem-19',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Physical Chemistry: Chemical & Ionic Equilibrium',
    topic: 'Chemical Kinetics',
    difficulty: 'hard',
    question: 'The activation energy of a chemical reaction is $E_a = 57.5\\,\\text{kJ/mol}$. When the temperature is raised from $300\\,\\text{K}$ to $310\\,\\text{K}$, the rate constant approximately increases by a factor of (take $R = 8.314\\,\\text{J/mol}\\cdot\\text{K}$):',
    options: [
      '$2.1$',
      '$4.0$',
      '$1.2$',
      '$10.0$'
    ],
    correctAnswer: 0,
    explanation: 'By Arrhenius equation: $\\ln\\left(\\frac{k_2}{k_1}\\right) = \\frac{E_a}{R}\\left(\\frac{1}{T_1} - \\frac{1}{T_2}\\right) = \\frac{E_a}{R} \\frac{\\Delta T}{T_1 T_2}$. Here $E_a = 57500\\,\\text{J/mol}$, $R = 8.314\\,\\text{J/mol}\\cdot\\text{K}$, $\\Delta T = 10\\,\\text{K}$, $T_1 T_2 = 300 \\times 310 = 93000\\,\\text{K}^2$. $\\ln\\left(\\frac{k_2}{k_1}\\right) = \\frac{57500}{8.314} \\times \\frac{10}{93000} = 6916 \\times 0.0001075 \\approx 0.7437$. Therefore, $\\frac{k_2}{k_1} = e^{0.7437} \\approx 2.1$.',
    solution: '1. $\\ln(k_2/k_1) = \\frac{57500}{8.314} \\times \\frac{10}{300 \\times 310} = 0.7437$.\n2. $k_2 / k_1 = e^{0.7437} \\approx 2.1$.',
    concepts: ['Arrhenius equation', 'Temperature coefficient of reaction rate', 'Activation energy calculation'],
    commonTrap: 'Assuming all reactions double every 10 degrees; temperature coefficient depends strictly on $E_a$. Here $E_a = 57.5\\,\\text{kJ/mol}$ corresponds to a factor of $2.1$.',
    shortcut: 'Rough rule of thumb: $E_a \\approx 50-60\\,\\text{kJ/mol}$ gives rate doubling ($2.0 - 2.2$) for a $10^\\circ$ rise near room temp.',
    hints: ['Apply the two-temperature Arrhenius equation.', 'Be careful with units: convert $E_a$ from $\\text{kJ}$ to $\\text{J}$.', 'Exponentiate the result to find $k_2/k_1$.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'chem-20',
    sourceType: 'ai_variation',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry: Mechanisms & Functional Groups',
    topic: 'Amines & Diazonium Salts',
    difficulty: 'very_hard',
    question: 'When aniline is treated with nitrous acid ($\\text{NaNO}_2 + \\text{HCl}$) at $0-5^\\circ\\text{C}$, it forms benzenediazonium chloride. However, when aliphatic primary amines (e.g. ethylamine) are treated under identical conditions, the primary observation is:',
    options: [
      'Rapid, brisk effervescence of nitrogen gas ($N_2$) with formation of a mixture of alcohols, alkenes, and alkyl halides',
      'Stable aliphatic diazonium salt that precipitates out as crystalline solid',
      'Predominant formation of ethyl nitrite without gas evolution',
      'No reaction occurs at $0-5^\\circ\\text{C}$'
    ],
    correctAnswer: 0,
    explanation: 'Aliphatic diazonium salts ($R-\\text{N}_2^+$) lack resonance stabilization because the alkyl group cannot delocalize the positive charge into an aromatic $\\pi$-system. Consequently, aliphatic diazonium ions are exceedingly unstable even at $0^\\circ\\text{C}$ and spontaneously decompose, eliminating molecular nitrogen gas ($N_2$) with brisk effervescence to generate highly reactive carbocations, which partition into alcohols, alkenes, and alkyl chlorides.',
    solution: '1. Aliphatic diazonium salts lack resonance stabilization.\n2. They decompose instantaneously: $R-N_2^+ \\to R^+ + N_2 \\uparrow$.\n3. Rapid evolution of $N_2$ gas is observed with formation of alcohol/alkene mixtures.',
    concepts: ['Diazotization of primary amines', 'Resonance stabilization of aryl vs alkyl diazonium ions', 'Carbocation partitioning'],
    commonTrap: 'Expecting aliphatic diazonium salts to be stable at $0-5^\\circ\\text{C}$ like benzenediazonium salts.',
    shortcut: 'Aliphatic primary amine + HNO2 = instantaneous N2 gas effervescence + alcohol mixture.',
    hints: ['Can an alkyl group provide resonance stabilization to the diazonium group?', 'What gas is released when a diazonium group breaks apart?', 'What happens to the carbocation formed after nitrogen leaves?'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 50
  },
  {
    id: 'chem-21',
    sourceType: 'verified_past',
    subject: 'Chemistry',
    chapter: 'Inorganic Chemistry: Coordination & Periodic Trends',
    topic: 'Coordination Compounds',
    difficulty: 'hard',
    question: 'How many geometrical and optical isomers are possible for the octahedral coordination complex $[\\text{Co}(\\text{en})_2\\text{Cl}_2]^+$ (where $\\text{en}$ is ethylenediamine)?',
    options: [
      '2 geometrical isomers (cis and trans), of which only the cis-isomer is optically active (total 3 stereoisomers)',
      '2 geometrical isomers, both optically active (total 4 stereoisomers)',
      '3 geometrical isomers, none optically active',
      'Only 1 isomer exists'
    ],
    correctAnswer: 0,
    explanation: '$[\\text{Co}(\\text{en})_2\\text{Cl}_2]^+$ exists as two geometrical isomers: (1) **trans-isomer**, where the two chloride ligands occupy opposite axial positions ($180^\\circ$). It possesses a plane of symmetry and an inversion center, making it achiral and optically inactive. (2) **cis-isomer**, where the chloride ligands occupy adjacent positions ($90^\\circ$). The cis-isomer lacks any plane of symmetry or center of inversion; it is non-superimposable on its mirror image and exists as a pair of enantiomers ($d$- and $l$-forms). Thus, there are 2 geometrical isomers and 3 total stereoisomers.',
    solution: '1. Geometrical isomers: cis and trans (2 geometrical isomers).\n2. Trans-isomer has an internal plane of symmetry $\\implies$ optically inactive.\n3. Cis-isomer is chiral (no plane of symmetry) $\\implies$ optically active (d and l enantiomers).\n4. Total stereoisomers = 1 trans + 2 cis enantiomers = 3.',
    concepts: ['Stereoisomerism in coordination complexes', 'Chirality in octahedral complexes', 'Bidentate chelate geometry'],
    commonTrap: 'Assuming the trans isomer is also optically active. Trans-$[\\text{Co}(\\text{en})_2\\text{Cl}_2]^+$ has a plane of symmetry!',
    shortcut: 'Cis-[M(AA)2B2] is always chiral (optically active); Trans-[M(AA)2B2] is achiral (inactive).',
    hints: ['Draw the cis and trans configurations with the bidentate ethylenediamine ligands.', 'Look for planes of symmetry in the trans isomer.', 'Does the cis isomer have any mirror plane?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 60
  }
];
