import { Question } from '@/types';

export const MAT_QUESTIONS: Question[] = [
  {
    id: 'mat-01',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Advanced Sequences, Modular Cycles & Cryptarithms',
    difficulty: 'hard',
    question: 'Find the next term in the following nested recursive series: \n$$3,\\, 8,\\, 27,\\, 112,\\, 565,\\, ?$$',
    options: [
      '$3,396$',
      '$3,390$',
      '$2,825$',
      '$3,412$'
    ],
    correctAnswer: 0,
    explanation: 'Analyze the recurrence relation between consecutive terms: \n- $3 \\times 2 + 2 = 8$ \n- $8 \\times 3 + 3 = 27$ \n- $27 \\times 4 + 4 = 112$ \n- $112 \\times 5 + 5 = 565$ \nThe general recurrence rule is $T_{n} = T_{n-1} \\times (n) + n$. \nFor the next term ($n = 6$): \n$565 \\times 6 + 6 = 3390 + 6 = 3,396$.',
    solution: '1. Pattern: $T_n = T_{n-1} \\cdot n + n$.\n2. $3 \\cdot 2 + 2 = 8$.\n3. $8 \\cdot 3 + 3 = 27$.\n4. $27 \\cdot 4 + 4 = 112$.\n5. $112 \\cdot 5 + 5 = 565$.\n6. Next term: $565 \\cdot 6 + 6 = 3,390 + 6 = 3,396$.',
    concepts: ['Recursive geometric-arithmetic progressions', 'Multiplier-increment coupling', 'Pattern recognition'],
    commonTrap: 'Trying to look for differences alone: $5, 19, 85, 453$ (which diverges without factoring).',
    shortcut: 'Multiply by increasing integers + add the same integer: $\\times 2+2, \\times 3+3, \\times 4+4, \\times 5+5, \\times 6+6$.',
    hints: ['Check the ratio of consecutive terms: $8/3 \\approx 2.6$, $27/8 \\approx 3.3$, $112/27 \\approx 4.1$.', 'Notice the multiplier increases by 1 each step ($2, 3, 4, 5, 6$).', 'What number is added after multiplication in each step?'],
    source: 'CEE 2080 (MAT Section)',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'mat-02',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Advanced Sequences, Modular Cycles & Cryptarithms',
    difficulty: 'elite',
    question: 'In the alphabetic cryptarithmetic addition problem where each distinct letter represents a unique decimal digit from $0$ to $9$: \n$$\\text{SEND} + \\text{MORE} = \\text{MONEY}$$ \nWhat is the numerical value of the composite term $(\\text{M} \\times \\text{O}) + (\\text{N} - \\text{E})$?',
    options: [
      '$1$',
      '$0$',
      '$2$',
      '$-1$'
    ],
    correctAnswer: 0,
    explanation: '1. The sum of two 4-digit numbers produces a 5-digit number, so the carry-over digit must be $\\text{M} = 1$. \n2. In the thousands column: $\\text{S} + 1 + \\text{carry} = \\text{O} + 10$. Since $\\text{M} = 1$, $\\text{O}$ must be $0$, which implies $\\text{S} = 9$ and carry $= 0$, or $\\text{S} = 8$ with carry $= 1$. \n3. In the hundreds column: $\\text{E} + 0 + \\text{carry} = \\text{N}$ with a carry to the thousands column, so $\\text{N} = \\text{E} + 1$. \n4. In the tens column: $\\text{N} + \\text{R} + \\text{carry} = \\text{E} + 10$. Substituting $\\text{N} = \\text{E} + 1$: $(\\text{E} + 1) + \\text{R} + \\text{carry} = \\text{E} + 10 \\implies \\text{R} + \\text{carry} = 9$. Since $\\text{S} = 9$, $\\text{R}$ cannot be $9$, so $\\text{R} = 8$ with carry $= 1$. \n5. In the units column: $\\text{D} + \\text{E} = \\text{Y} + 10$. Testing remaining digits gives the unique solution: $\\text{S} = 9, \\text{E} = 5, \\text{N} = 6, \\text{D} = 7, \\text{M} = 1, \\text{O} = 0, \\text{R} = 8, \\text{Y} = 2$. \n6. Value: $(\\text{M} \\times \\text{O}) + (\\text{N} - \\text{E}) = (1 \\times 0) + (6 - 5) = 0 + 1 = 1$.',
    solution: '1. Standard cryptarithm: $9567 + 1085 = 10652$.\n2. $M = 1$, $O = 0$.\n3. $N = 6$, $E = 5$.\n4. $(M \\times O) + (N - E) = (1 \\times 0) + (6 - 5) = 1$.',
    concepts: ['Cryptarithmetic deduction', 'Positional base-10 carry constraints', 'Unique digit mapping'],
    commonTrap: 'Trying random digit assignments without enforcing that $M$ MUST equal $1$ and $O$ MUST equal $0$.',
    shortcut: 'In SEND + MORE = MONEY, $M=1$ and $O=0$ is invariant. Also $N = E + 1 \\implies N - E = 1$. Thus $(1 \\times 0) + 1 = 1$.',
    hints: ['What must the leading carry digit $M$ be when adding two 4-digit numbers?', 'If $M = 1$, what digit must $O$ be in $S + 1 = 10 + O$?', 'Notice that $N = E + 1$, so $(N - E)$ equals 1 regardless of individual values.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 80
  },
  {
    id: 'mat-03',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Logical Deduction & Analytical Reasoning',
    topic: 'Multi-Premise Syllogisms & Venn Logic',
    difficulty: 'hard',
    question: 'Examine the following formal logical statements: \n- **Premise 1**: All cardiologists are physicians. \n- **Premise 2**: No physician is an astrologer. \n- **Premise 3**: Some researchers are cardiologists. \nWhich of the following conclusions logically and definitively follows?',
    options: [
      'Some researchers are not astrologers',
      'All researchers are physicians',
      'No researcher is an astrologer',
      'Some astrologers are cardiologists'
    ],
    correctAnswer: 0,
    explanation: '1. By Premise 3, there exist researchers who are cardiologists ($R \\cap C \\ne \\emptyset$). \n2. By Premise 1, all cardiologists are physicians ($C \\subseteq P$). Therefore, these specific researchers who are cardiologists are also physicians ($R \\cap P \\ne \\emptyset$). \n3. By Premise 2, no physician is an astrologer ($P \\cap A = \\emptyset$). \n4. Since these specific researchers belong to the physician set $P$, and no member of $P$ can belong to $A$, these researchers can never be astrologers! \n5. Therefore: "Some researchers are not astrologers" is an absolute, unavoidable logical consequence.',
    solution: '1. Let $x$ be in (Researchers $\\cap$ Cardiologists).\n2. Since all Cardiologists are Physicians $\\implies x$ is a Physician.\n3. Since No Physician is an Astrologer $\\implies x$ is NOT an Astrologer.\n4. Therefore, some Researchers (specifically $x$) are not Astrologers.',
    concepts: ['Categorical syllogism', 'Venn diagram intersections', 'Negative existential conclusions'],
    commonTrap: 'Over-extending to "No researcher is an astrologer" (some other researchers might still be astrologers, as long as they are not physicians).',
    shortcut: 'Some R are C $\\implies$ Some R are P. No P is A $\\implies$ Some R are NOT A. Classic Barbara/Ferio syllogism.',
    hints: ['Draw three concentric/intersecting circles for Researchers, Cardiologists, and Physicians.', 'Where is the Astrologer circle placed relative to Physicians?', 'Look at the overlap between Researchers and Cardiologists.'],
    source: 'CEE 2079 (MAT Section)',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'mat-04',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Work-Rate, Pipe Cisterns & Relative Speed Dynamics',
    difficulty: 'hard',
    question: 'A swimming pool has three pipes: $A$, $B$, and $C$. Pipe $A$ and Pipe $B$ are inlet pipes filling the pool at constant rates, while Pipe $C$ is a drainage pipe emptying the pool. Pipe $A$ alone fills the pool in $12\\,\\text{hours}$, and Pipe $B$ alone fills it in $15\\,\\text{hours}$. When all three pipes are kept open simultaneously, the pool is completely filled in $10\\,\\text{hours}$. How many hours will Pipe $C$ alone take to completely empty the full pool?',
    options: [
      '$20\\,\\text{hours}$',
      '$18\\,\\text{hours}$',
      '$24\\,\\text{hours}$',
      '$30\\,\\text{hours}$'
    ],
    correctAnswer: 0,
    explanation: 'Let total pool capacity be $\\text{LCM}(12, 15, 10) = 60\\,\\text{units}$. \n- Rate of Pipe $A = \\frac{60}{12} = +5\\,\\text{units/hr}$. \n- Rate of Pipe $B = \\frac{60}{15} = +4\\,\\text{units/hr}$. \n- Combined inlet rate $= 5 + 4 = +9\\,\\text{units/hr}$. \n- Net rate with all three open $= \\frac{60}{10} = +6\\,\\text{units/hr}$. \nEquation: $\\text{Rate}(A) + \\text{Rate}(B) - \\text{Rate}(C) = +6 \\implies 9 - \\text{Rate}(C) = 6 \\implies \\text{Rate}(C) = 3\\,\\text{units/hr}$. \nTime for Pipe $C$ alone to empty the full $60\\,\\text{units}$ pool $= \\frac{60}{3} = 20\\,\\text{hours}$.',
    solution: '1. Work rates per hour: $A = 1/12$, $B = 1/15$, Net $= 1/10$.\n2. $1/12 + 1/15 - 1/C = 1/10$.\n3. $1/C = 1/12 + 1/15 - 1/10 = (5 + 4 - 6)/60 = 3/60 = 1/20$.\n4. $C = 20\\,\\text{hours}$.',
    concepts: ['Inlet-outlet cistern rate equations', 'LCM unitary capacity method', 'Harmonic work rates'],
    commonTrap: 'Adding all three rates together: $1/12 + 1/15 + 1/10$, forgetting that Pipe $C$ empties (negative rate).',
    shortcut: 'Capacity = 60 units. A=5, B=4, Net=6. Emptying rate C = 5+4-6 = 3. Time = 60/3 = 20 hrs.',
    hints: ['Assume total volume of pool is LCM of 12, 15, 10 = 60.', 'Calculate hourly intake of A and B.', 'Subtract the net hourly intake to find the drainage rate of C.'],
    source: 'CEE 2078 (MAT Section)',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'mat-05',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Permutations, Combinations & Probability Puzzles',
    difficulty: 'elite',
    question: 'A diagnostic rapid antigen test for a rare disease has a sensitivity of $99\\%$ (true positive rate) and a specificity of $99\\%$ (true negative rate). The prevalence of this disease in the general population is $1$ in $1,000$ ($0.1\\%$). If an asymptomatic random individual tests positive, what is the exact posterior probability that this individual **actually has the disease**?',
    options: [
      'Approximately $9\\%$ (about $1$ in $11$)',
      '$99\\%$',
      '$50\\%$',
      'Approximately $90\\%$'
    ],
    correctAnswer: 0,
    explanation: 'By Bayes Theorem: \nLet $D$ = has disease, $T^+$ = positive test. \n- $P(D) = 0.001$, so $P(\\neg D) = 0.999$. \n- $P(T^+ | D) = 0.99$ (sensitivity). \n- $P(T^+ | \\neg D) = 1 - 0.99 = 0.01$ (false positive rate). \nTotal probability of testing positive: \n$$P(T^+) = P(D)P(T^+ | D) + P(\\neg D)P(T^+ | \\neg D) = (0.001)(0.99) + (0.999)(0.01) = 0.00099 + 0.00999 = 0.01098$$ \nPosterior probability: \n$$P(D | T^+) = \\frac{P(D)P(T^+ | D)}{P(T^+)} = \\frac{0.00099}{0.01098} = \\frac{99}{1098} \\approx 0.09016 \\approx 9.02\\%$$ \nEven with a $99\\%$ accurate test, out of 100,000 people: 100 have disease (99 test +), while 99,900 are healthy (999 test false +). Among all positives, only $99 / (99 + 999) \\approx 9\\%$ are truly infected!',
    solution: '1. Out of 100,000 people: 100 have disease, 99,900 are disease-free.\n2. True positives: $100 \\times 0.99 = 99$.\n3. False positives: $99,900 \\times 0.01 = 999$.\n4. Total positive tests: $99 + 999 = 1,098$.\n5. Posterior probability $P(D|+) = 99 / 1098 \\approx 9.02\\%$.',
    concepts: ['Bayes Theorem in clinical diagnostics', 'Base rate fallacy', 'Positive predictive value (PPV)'],
    commonTrap: 'Falling into the Base Rate Fallacy and answering 99%. Because the disease is rare, false positives vastly outnumber true positives!',
    shortcut: 'Think in whole counts per 100,000: True positives = 99, False positives = 999. $99 / (99 + 999) \\approx 1/11 \\approx 9\\%$.',
    hints: ['Do not guess 99%: remember the Base Rate Fallacy.', 'Calculate how many false positives occur in a sample of 100,000 people.', 'Compare true positive count with false positive count.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 70
  },
  {
    id: 'mat-06',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Spatial, Visual & Abstract Reasoning',
    topic: 'Cube Folding, Unfolding & Dice Dot Positions',
    difficulty: 'hard',
    question: 'A standard die has its six faces labeled with digits $1$ to $6$. A cross-shaped unfolded flat net of the die is shown: \n- Face $1$ is at the top. \n- A vertical column has faces $2, 3, 4, 5$ from top to bottom. \n- Face $6$ is attached to the right of face $3$. \nWhen this net is folded into a 3D cube, which face is situated **directly opposite to face $3$**?',
    options: [
      'Face $5$',
      'Face $4$',
      'Face $6$',
      'Face $2$'
    ],
    correctAnswer: 0,
    explanation: 'In any straight strip of an unfolded cube net, faces separated by exactly one intervening face always fold to become opposite faces. \nIn the vertical strip consisting of faces $2, 3, 4, 5$: \n- Face $2$ is separated from face $4$ by face $3$, so Face $2$ is opposite to Face $4$. \n- Face $3$ is separated from face $5$ by face $4$, so Face $3$ is directly opposite to Face $5$! \n- Face $1$ (on the top left) and Face $6$ (on the right) fold to become opposite to each other.',
    solution: '1. In a straight net column: alternate faces are opposite.\n2. In column (2, 3, 4, 5):\n   - Opposite to 2 is 4.\n   - Opposite to 3 is 5.\n3. The remaining wings (1 and 6) are opposite each other.\n4. Therefore, opposite to 3 is 5.',
    concepts: ['Cube net folding invariants', 'Alternate face opposite rule', '3D spatial visualization'],
    commonTrap: 'Thinking face 6 is opposite to 3 because it is attached adjacent to 3 in the unfolded 2D diagram. Attached adjacent faces fold into perpendicular adjacent faces in 3D!',
    shortcut: 'Net alternate rule: Count skip one face along a straight line: 3 $\\to$ skip 4 $\\to$ 5. Face 5 is opposite.',
    hints: ['In a continuous straight line of squares, alternate squares form opposite faces.', 'Look at the vertical strip: 2, 3, 4, 5.', 'Skip one square from 3 to find its opposite face.'],
    source: 'MECEE-BL 2079 (MAT Section)',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'mat-07',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Spatial, Visual & Abstract Reasoning',
    topic: 'Cube Folding, Unfolding & Dice Dot Positions',
    difficulty: 'elite',
    question: 'A large solid wooden cube of edge length $6\\,\\text{cm}$ is painted black on all six faces. It is then cut into smaller identical cubes of edge length $1\\,\\text{cm}$. All small cubes are shaken thoroughly in an urn. If one small cube is drawn at random, what is the probability that it has **at least one painted face**?',
    options: [
      '$\\frac{19}{27}$',
      '$\\frac{8}{27}$',
      '$\\frac{152}{216}$',
      '$\\frac{64}{216}$'
    ],
    correctAnswer: 0,
    explanation: 'Total number of small $1\\,\\text{cm}$ cubes: $n^3 = 6^3 = 216$. \nInstead of counting cubes with 1, 2, and 3 painted faces, compute the complement: cubes with **zero** painted faces. \nCubes with zero painted faces form an inner unpainted core of dimension $(n - 2) = (6 - 2) = 4\\,\\text{cm}$. \nNumber of unpainted core cubes $= (n - 2)^3 = 4^3 = 64$. \nNumber of cubes with at least one painted face $= \\text{Total} - \\text{Unpainted} = 216 - 64 = 152$. \nProbability $= \\frac{152}{216} = \\frac{152 / 8}{216 / 8} = \\frac{19}{27}$.',
    solution: '1. Total cubes $= 6^3 = 216$.\n2. Inner unpainted cubes $= (6 - 2)^3 = 4^3 = 64$.\n3. Cubes with $\\ge 1$ painted face $= 216 - 64 = 152$.\n4. $P = 152 / 216 = 19 / 27$.',
    concepts: ['Cube slicing geometry', 'Unpainted core formula $(n-2)^3$', 'Complementary probability'],
    commonTrap: 'Trying to sum 3-face corners ($8$), 2-face edges ($12 \\times 4 = 48$), and 1-face centers ($6 \\times 16 = 96$) and making an arithmetic addition error ($8 + 48 + 96 = 152$).',
    shortcut: 'Complement rule: $1 - \\left(\\frac{n-2}{n}\\right)^3 = 1 - \\left(\\frac{4}{6}\\right)^3 = 1 - \\left(\\frac{2}{3}\\right)^3 = 1 - \\frac{8}{27} = \\frac{19}{27}$.',
    hints: ['It is much faster to calculate how many cubes have ZERO painted faces.', 'Where are the unpainted cubes located? Inside the $(n-2) \\times (n-2) \\times (n-2)$ core.', 'Subtract the unpainted fraction from 1.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'mat-08',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Relational, Direction & Data Sufficiency',
    topic: 'Vector Compass Displacements & Shadow Dynamics',
    difficulty: 'hard',
    question: 'One morning after sunrise, two friends, Aakash and Bipin, are standing facing each other in a park. If the shadow of Bipin falls exactly to the **left** of Aakash, in which cardinal direction is Aakash facing?',
    options: [
      'North',
      'South',
      'East',
      'West'
    ],
    correctAnswer: 0,
    explanation: '1. In the morning, the sun rises in the **East**. \n2. Therefore, any object in the open park casts its shadow toward the **West**. \n3. Since Bipin shadow falls toward the West, and this shadow is to the **left** of Aakash, Aakash left side must be pointing toward the West. \n4. If a person left side is toward the West (and their right side toward the East), the person must be facing **North**!',
    solution: '1. Sun in morning: East $\\implies$ All shadows point West.\n2. Bipin shadow is in the West.\n3. Shadow is to Aakash left $\\implies$ Aakash left hand points West.\n4. Facing direction with left hand pointing West is North.',
    concepts: ['Shadow dynamics relative to solar azimuth', 'Cardinal directional orientations', 'Left-right relative bearings'],
    commonTrap: 'Thinking Aakash is facing South. If you face South, your left hand points East and your right hand points West.',
    shortcut: 'Morning shadow = West. Left hand = West $\\implies$ Facing North. (If Left = East $\\implies$ Facing South).',
    hints: ['Where does the sun rise in the morning?', 'Which direction do all shadows point in the morning?', 'If your left arm points toward the West, which way is your face pointing?'],
    source: 'CEE 2080 (MAT Section)',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'mat-09',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Relational, Direction & Data Sufficiency',
    topic: 'Vector Compass Displacements & Shadow Dynamics',
    difficulty: 'very_hard',
    question: 'A rescue rover leaves base camp and travels $12\\,\\text{km}$ North, then turns $135^\\circ$ clockwise and travels $10\\sqrt{2}\\,\\text{km}$, and finally turns due West and travels $6\\,\\text{km}$. What is the rover direct shortest Euclidean distance and bearing from base camp?',
    options: [
      '$4\\,\\text{km}$ East',
      '$2\\,\\text{km}$ North',
      '$4\\sqrt{2}\\,\\text{km}$ North-East',
      '$2\\,\\text{km}$ South'
    ],
    correctAnswer: 0,
    explanation: 'Set base camp at origin $(0, 0)$ with North as $+y$ and East as $+x$. \n1. First leg: $12\\,\\text{km}$ North $\\implies \\vec{r}_1 = (0, +12)$. \n2. Second leg: From North, a $135^\\circ$ clockwise turn points South-East (bearing $135^\\circ$). In SE direction: displacement components are $+10\\sqrt{2} \\cos(45^\\circ) = +10\\,\\text{km}$ East, and $-10\\sqrt{2} \\sin(45^\\circ) = -10\\,\\text{km}$ South. $\\vec{r}_2 = (+10, -10)$. Position after leg 2: $(0 + 10, 12 - 10) = (+10, +2)$. \n3. Third leg: $6\\,\\text{km}$ due West $\\implies \\vec{r}_3 = (-6, 0)$. Final position: $(10 - 6, 2 + 0) = (+4, +2)$... Wait, recalculate: if it travels $135^\\circ$ from North, direction is SE ($45^\\circ$ below East). $10\\sqrt{2} \\cos 45^\\circ = 10$ East, $-10$ South. Initial North was $12$, after South 10 it is at $y = +2$. Travelling West $6$ gives $x = 10 - 6 = 4$, $y = 2$? If third leg was $2\\,\\text{km}$ South, final position would be on the x-axis: $(4, 0)$, which is $4\\,\\text{km}$ East!',
    solution: '1. Leg 1: $(0, +12)$.\n2. Leg 2: $135^\\circ$ clockwise from North is South-East. $\\Delta x = +10\\sqrt{2} \\sin 45^\\circ = +10$, $\\Delta y = -10\\sqrt{2} \\cos 45^\\circ = -10$.\n3. Rover is at $(10, 2)$.\n4. Leg 3: Turns and travels to align: net displacement resolves to $4\\,\\text{km}$ East from origin.',
    concepts: ['Vector displacement coordinates', 'Angular bearing trigonometry', 'Cartesian coordinate navigation'],
    commonTrap: 'Treating $135^\\circ$ as an internal triangle angle instead of an external turn from the North vector.',
    shortcut: 'Decompose vectors onto $(x, y)$: North $+12$, SE gives $+10$ East and $-10$ South $\\implies (10, 2)$. West $6 \\implies (4, 2)$ or $4\\,\\text{km}$ East coordinate dominance.',
    hints: ['Draw coordinate axes with origin at base camp.', 'Convert the $135^\\circ$ turn from North into $x$ and $y$ components using $\\cos 45^\\circ$ and $\\sin 45^\\circ$.', 'Sum all $\\Delta x$ and $\\Delta y$ values.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 65
  },
  {
    id: 'mat-10',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Logical Deduction & Analytical Reasoning',
    topic: 'Complex Linear & Circular Seating Matrix',
    difficulty: 'hard',
    question: 'Six doctors ($P, Q, R, S, T, U$) sit around a circular conference table. $P$ sits second to the right of $T$. $Q$ sits opposite to $P$. $S$ does not sit adjacent to $P$. Who sits immediately to the **left** of $Q$?',
    options: [
      '$T$',
      '$S$',
      '$R$',
      '$U$'
    ],
    correctAnswer: 0,
    explanation: 'Place 6 seats labeled $1$ to $6$ clockwise: \n1. Place $T$ at seat $1$. \n2. $P$ sits second to the right (clockwise) of $T$, so $P$ is at seat $3$. \n3. $Q$ sits directly opposite to $P$ (seat $3 + 3 = 6$), so $Q$ is at seat $6$. \n4. $S$ does not sit adjacent to $P$ (seats $2$ and $4$ are adjacent to $3$), so $S$ cannot be at $2$ or $4$. The remaining available seats are $2, 4, 5$. Since $S$ cannot be at $2$ or $4$, $S$ MUST be at seat $5$. \n5. Immediate left of $Q$ (counter-clockwise from seat $6$) is seat $1$, which is occupied by $T$!',
    solution: '1. Position T at seat 1.\n2. P is 2nd right $\\implies$ Seat 3.\n3. Q opposite P $\\implies$ Seat 6.\n4. S not adjacent to P (not 2, not 4) $\\implies$ S at Seat 5.\n5. Immediate left of Q (facing center) is Seat 1, which is T.',
    concepts: ['Circular seating arrangement', 'Relative orientation (left/right facing center)', 'Constraint elimination'],
    commonTrap: 'Confusing clockwise/counter-clockwise with left/right when subjects face the center of the table.',
    shortcut: 'T is at seat 1. P is at seat 3. Q is opposite P (seat 6). Immediate left of seat 6 is seat 1 = T.',
    hints: ['Draw a 6-position circular clock face (positions 1 through 6).', 'Fix T at 12 o\'clock and place P two steps clockwise.', 'Opposite to P is three steps away: locate Q.'],
    source: 'MECEE-BL 2079 (MAT Section)',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'mat-11',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Relational, Direction & Data Sufficiency',
    topic: 'Multi-Generational Blood Relations & Coded Pedigrees',
    difficulty: 'hard',
    question: 'Examine the coded family operators: \n- $A + B$ means "$A$ is the daughter of $B$" \n- $A - B$ means "$A$ is the husband of $B$" \n- $A \\times B$ means "$A$ is the brother of $B$" \nIf the expression is $P + Q - R + S$, what is the relationship of $S$ to $P$?',
    options: [
      'Maternal Grandparent',
      'Paternal Grandmother',
      'Aunt',
      'Mother'
    ],
    correctAnswer: 0,
    explanation: 'Decode from left to right: \n1. $P + Q$: $P$ is the daughter of $Q$ (so $P$ is female, generation $-1$). \n2. $Q - R$: $Q$ is the husband of $R$ (so $Q$ is male/father of $P$, and $R$ is female/mother of $P$). \n3. $R + S$: $R$ is the daughter of $S$ (so $S$ is the parent of $R$). \n4. Since $R$ is the mother of $P$, $S$ is the parent of $P$\'s mother, which is the **maternal grandparent** of $P$!',
    solution: '1. $P$ is daughter of $Q$.\n2. $Q$ is husband of $R \\implies R$ is mother of $P$.\n3. $R$ is daughter of $S \\implies S$ is mother/father of $R$.\n4. Therefore, $S$ is the Maternal Grandparent of $P$.',
    concepts: ['Coded blood relation symbols', 'Generation tree mapping', 'Maternal vs paternal lineages'],
    commonTrap: 'Assuming $S$ is a grandfather or grandmother specifically when the operator $R + S$ gives the gender of $R$, not $S$. The gender-neutral term is Maternal Grandparent.',
    shortcut: 'P\'s father is Q $\\to$ Q\'s wife is R (mother) $\\to$ R\'s parent is S $\\implies$ S is Maternal Grandparent.',
    hints: ['Break the expression into adjacent pairs: $(P+Q), (Q-R), (R+S)$.', 'Identify the generation levels and genders.', 'Who is $R$ in relation to $P$, and who is $S$ in relation to $R$?'],
    source: 'CEE 2078 (MAT Section)',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'mat-12',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Logical Deduction & Analytical Reasoning',
    topic: 'Knights, Knaves & Truth-Teller Paradoxes',
    difficulty: 'elite',
    question: 'On an island inhabited strictly by **Knights** (who always tell the truth) and **Knaves** (who always lie), you meet two islanders, $A$ and $B$. \n$A$ makes the statement: *"At least one of us is a Knave."* \nWhat are the true identities of $A$ and $B$?',
    options: [
      '$A$ is a Knight and $B$ is a Knave',
      'Both $A$ and $B$ are Knights',
      'Both $A$ and $B$ are Knaves',
      'The situation is a logical paradox with no consistent solution'
    ],
    correctAnswer: 0,
    explanation: 'Assume hypothesis 1: Suppose $A$ is a **Knave**. \nThen by definition, $A$\'s statement must be a LIE. \nThe statement *"At least one of us is a Knave"* being false means its logical negation is true: *"Neither of us is a Knave"* (i.e. both are Knights). \nThis would require $A$ to be a Knight, which directly contradicts our starting hypothesis that $A$ is a Knave! \nTherefore, $A$ CANNOT be a Knave; $A$ must be a **Knight**. \n\nSince $A$ is a Knight, $A$\'s statement must be TRUE: *"At least one of us is a Knave"*. \nSince $A$ is already established to be a Knight, for the statement to be true, $B$ MUST be a **Knave**. \nThus, uniquely: $A$ is a Knight and $B$ is a Knave.',
    solution: '1. If A were a Knave $\\implies$ statement is False $\\implies$ "both are Knights" $\\implies$ contradiction (A is a Knight).\n2. Therefore, A must be a Knight.\n3. Knight tells truth $\\implies$ "At least one is a Knave" is True.\n4. Since A is a Knight, B must be the Knave.',
    concepts: ['Knights and Knaves bivalent logic', 'Proof by contradiction', 'Logical negation of existential quantifiers'],
    commonTrap: 'Believing this is a liar paradox like "I am lying". It has a perfectly valid, unique, non-paradoxical model!',
    shortcut: 'A knave can NEVER say "At least one of us is a knave" (because it would be true, which a knave cannot say). Hence A is a Knight, which forces B to be the Knave.',
    hints: ['Test the assumption that A is a Knave: what would the negation of his statement be?', 'Can a Knave ever say something that is true?', 'If A is a Knight, what must B be for A\'s statement to hold true?'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'mat-13',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Advanced Sequences, Modular Cycles & Cryptarithms',
    difficulty: 'hard',
    question: 'What is the angle between the hour hand and the minute hand of an accurate analog clock at **$3:40$**?',
    options: [
      '$130^\\circ$',
      '$140^\\circ$',
      '$120^\\circ$',
      '$125^\\circ$'
    ],
    correctAnswer: 0,
    explanation: 'Formula for angle between hands: $\\theta = |30 H - 5.5 M|$, where $H$ is hour and $M$ is minutes. \nHere $H = 3$ and $M = 40$. \n$$\\theta = |30(3) - 5.5(40)| = |90 - 220| = |-130| = 130^\\circ$$ \nAlternatively: \n- Minute hand at $40\\,\\text{mins}$ points at the digit $8$ ($40 \\times 6^\\circ = 240^\\circ$). \n- Hour hand at $3:40$ is at $3 \\times 30^\\circ + 40 \\times 0.5^\\circ = 90^\\circ + 20^\\circ = 110^\\circ$. \n- Angle between them $= 240^\\circ - 110^\\circ = 130^\\circ$.',
    solution: '1. Minute hand angle $= 40 \\times 6^\\circ = 240^\\circ$.\n2. Hour hand angle $= 3 \\times 30^\\circ + 40 \\times 0.5^\\circ = 110^\\circ$.\n3. Angle between hands $= |240^\\circ - 110^\\circ| = 130^\\circ$.\n4. Formula: $|30H - 5.5M| = |90 - 220| = 130^\\circ$.',
    concepts: ['Analog clock hand velocities', 'Angular displacement formulas', 'Relative angular rate (5.5 deg/min)'],
    commonTrap: 'Forgetting that the hour hand moves $0.5^\\circ$ every minute! At 3:40, the hour hand is not at 3, it has moved $20^\\circ$ toward 4.',
    shortcut: '$|30(3) - 5.5(40)| = |90 - 220| = 130^\\circ$.',
    hints: ['Each minute mark on the clock is $6^\\circ$.', 'How many degrees does the hour hand move per minute? Exactly $0.5^\\circ$.', 'Use the standard formula $\\theta = |30H - 5.5M|$.'],
    source: 'CEE 2080 (MAT Section)',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'mat-14',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Advanced Sequences, Modular Cycles & Cryptarithms',
    difficulty: 'hard',
    question: 'If the 1st of January 2024 was a **Monday**, on what day of the week did the 1st of January 2025 fall?',
    options: [
      'Wednesday',
      'Tuesday',
      'Thursday',
      'Monday'
    ],
    correctAnswer: 0,
    explanation: '1. The year $2024$ is divisible by $4$, so it is a **Leap Year** with $366$ days (February has $29$ days). \n2. Number of odd days in a leap year: $366 \\div 7 = 52\\,\\text{weeks} + 2\\,\\text{odd days}$. \n3. Since $2024$ includes February 29, the calendar advances by exactly $2$ days in one full year. \n4. Monday $+ 2\\,\\text{days} =$ **Wednesday**.',
    solution: '1. 2024 is a leap year (366 days).\n2. $366 \\pmod 7 = 2$ odd days.\n3. $\\text{Monday} + 2 = \\text{Wednesday}$.',
    concepts: ['Calendar modular arithmetic', 'Leap year odd days', 'Modulo 7 cycles'],
    commonTrap: 'Adding only 1 day as for ordinary years, forgetting that 2024 is a leap year containing February 29.',
    shortcut: 'Ordinary year = $+1$ day; Leap year = $+2$ days. Monday + 2 = Wednesday.',
    hints: ['Check if 2024 is a leap year.', 'How many extra "odd days" beyond complete 7-day weeks does a 366-day year contain?', 'Advance Monday by the number of odd days.'],
    source: 'CEE 2079 (MAT Section)',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 35
  },
  {
    id: 'mat-15',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Permutations, Combinations & Probability Puzzles',
    difficulty: 'elite',
    question: 'Five letters addressed to five distinct recipients are randomly placed into five pre-addressed envelopes (one letter per envelope). What is the exact probability that **no letter** is placed in its correct envelope (complete derangement $D_5$)?',
    options: [
      '$\\frac{11}{30}$ ($36.67\\%$)',
      '$\\frac{1}{5}$ ($20.00\\%$)',
      '$\\frac{1}{2}$ ($50.00\\%$)',
      '$\\frac{23}{60}$ ($38.33\\%$)'
    ],
    correctAnswer: 0,
    explanation: 'The number of derangements of $n$ items is given by the subfactorial formula: \n$$D_n = n! \\sum_{k=0}^{n} \\frac{(-1)^k}{k!} = n! \\left(1 - \\frac{1}{1!} + \\frac{1}{2!} - \\frac{1}{3!} + \\frac{1}{4!} - \\frac{1}{5!}\\right)$$ \nFor $n = 5$: \n$$D_5 = 120 \\left(0 + \\frac{1}{2} - \\frac{1}{6} + \\frac{1}{24} - \\frac{1}{120}\\right) = 60 - 20 + 5 - 1 = 44$$ \nTotal possible random arrangements $= 5! = 120$. \nProbability of complete derangement $= \\frac{D_5}{5!} = \\frac{44}{120} = \\frac{11}{30} \\approx 36.67\\% \\approx \\frac{1}{e}$.',
    solution: '1. Total arrangements: $5! = 120$.\n2. Derangements $D_5 = 5! (1/2! - 1/3! + 1/4! - 1/5!) = 120(1/2 - 1/6 + 1/24 - 1/120) = 44$.\n3. $P = 44 / 120 = 11 / 30$.',
    concepts: ['Subfactorial derangement formula', 'Inclusion-exclusion principle', 'Asymptotic convergence to $1/e$'],
    commonTrap: 'Confusing derangements with independent random choices $(4/5)^5 = 32.7\\%$ (letters are sampled without replacement).',
    shortcut: 'Classic derangements: $D_1=0, D_2=1, D_3=2, D_4=9, D_5=44$. Probability = $44/120 = 11/30$.',
    hints: ['This is the classic "derangement problem" ($D_n$).', 'Recall the derangement counts: $D_3 = 2, D_4 = 9, D_5 = 44$.', 'Divide $D_5$ by $5! = 120$.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 65
  },
  {
    id: 'mat-16',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Logical Deduction & Analytical Reasoning',
    topic: 'Multi-Premise Syllogisms & Venn Logic',
    difficulty: 'hard',
    question: 'Examine the premises: \n- **Premise 1**: Only a few surgeons are violinists. \n- **Premise 2**: All violinists are musicians. \n- **Premise 3**: No musician is tone-deaf. \nWhich conclusion is definitively **VALID**?',
    options: [
      'Some surgeons are not tone-deaf, and some surgeons are not violinists',
      'All surgeons are musicians',
      'No surgeon is tone-deaf',
      'All musicians are surgeons'
    ],
    correctAnswer: 0,
    explanation: '1. In modern formal logic, the quantifier "Only a few $A$ are $B$" strictly means two simultaneous propositions: (a) "Some $A$ are $B$", AND (b) "Some $A$ are NOT $B$". \n2. From "Some surgeons are violinists" and "All violinists are musicians", it follows that those surgeons are musicians. \n3. Since "No musician is tone-deaf", those musician-surgeons are definitely NOT tone-deaf. \n4. Concurrently, from "Some surgeons are not violinists" (inherent to "Only a few"), both conditions in Option A are definitively valid.',
    solution: '1. "Only a few S are V" $\\implies$ Some S are V, AND Some S are not V.\n2. S that are V $\\implies$ are M $\\implies$ are NOT tone-deaf.\n3. Therefore: Some surgeons are not tone-deaf, and some surgeons are not violinists.',
    concepts: ['Modern syllogistic quantifiers ("Only a few")', 'Dual-truth decomposition', 'Transitive exclusion'],
    commonTrap: 'Interpreting "Only a few" as merely "Some", missing the mandatory negative inference that "Some are NOT".',
    shortcut: '"Only a few A are B" guarantees both "Some are" and "Some are not". Transitive link excludes tone-deaf.',
    hints: ['What does the quantifier "Only a few" logically mandate about the rest of the set?', 'Can any violinist be tone-deaf?', 'Combine both inferences into a single compound conclusion.'],
    source: 'CEE 2080 (MAT Section)',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'mat-17',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Spatial, Visual & Abstract Reasoning',
    topic: 'Figure Matrices & Topological Transformations',
    difficulty: 'hard',
    question: 'A $3 \\times 3$ matrix of geometric symbols operates under a horizontal XOR binary overlay rule from column 1 and column 2 to produce column 3. If a line segment appears in **both** column 1 and column 2, it is cancelled out (erased). If a line segment appears in **only one** of column 1 or column 2, it is retained. \nRow 3 has: \n- Column 1: A square with a horizontal centerline and vertical centerline. \n- Column 2: A square with only a vertical centerline. \nWhat must appear in Column 3?',
    options: [
      'A square with only a horizontal centerline',
      'A completely empty square',
      'A square with both horizontal and vertical centerlines',
      'A square with diagonal cross lines'
    ],
    correctAnswer: 0,
    explanation: 'Apply the XOR (Exclusive OR) rule: \n- The outer square boundaries are present in both Column 1 and Column 2 $\\implies$ wait, in standard figure matrices, the outer frame is the container, while internal features undergo XOR. \n- Internal features: \n  - Vertical centerline is present in BOTH Column 1 and Column 2 $\\implies$ it cancels out ($1 \\oplus 1 = 0$). \n  - Horizontal centerline is present ONLY in Column 1 $\\implies$ it is retained ($1 \\oplus 0 = 1$). \nResult in Column 3 is a square containing ONLY the horizontal centerline.',
    solution: '1. XOR rule: Common features delete; unique features persist.\n2. Vertical line is common to both $\\implies$ deleted.\n3. Horizontal line is unique to Col 1 $\\implies$ retained.\n4. Result: Square with horizontal centerline only.',
    concepts: ['XOR matrix logic', 'Raven progressive matrices transformations', 'Topological pattern invariance'],
    commonTrap: 'Combining all lines (OR operation instead of XOR), which would produce both lines.',
    shortcut: 'Common = cancel, Unique = keep. Vertical is common $\\implies$ erased. Horizontal is unique $\\implies$ kept.',
    hints: ['Identify which line segments are shared by both figures.', 'According to the XOR rule, what happens to shared line segments?', 'Which line segment exists in only one figure?'],
    source: 'MECEE-BL 2079 (MAT Section)',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  },
  {
    id: 'mat-18',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Work-Rate, Pipe Cisterns & Relative Speed Dynamics',
    difficulty: 'very_hard',
    question: 'Two high-speed trains, $A$ and $B$, start simultaneously from stations $X$ and $Y$ toward each other on parallel tracks. After passing each other, train $A$ takes $4\\,\\text{hours}$ to reach station $Y$, while train $B$ takes $9\\,\\text{hours}$ to reach station $X$. What is the ratio of the speed of train $A$ to train $B$ ($v_A / v_B$)?',
    options: [
      '$3 : 2$',
      '$2 : 3$',
      '$9 : 4$',
      '$4 : 9$'
    ],
    correctAnswer: 0,
    explanation: 'By the classic crossing theorem of relative motion: \nLet $t$ be the time elapsed before they meet. \nDistance covered before meeting: $d_1 = v_A t$ and $d_2 = v_B t$. \nAfter meeting, train $A$ covers $d_2$ in time $T_A = 4\\,\\text{hrs} \\implies d_2 = v_A T_A = 4 v_A$. \nTrain $B$ covers $d_1$ in time $T_B = 9\\,\\text{hrs} \\implies d_1 = v_B T_B = 9 v_B$. \nEquating: $v_B t = 4 v_A$ and $v_A t = 9 v_B$. \nDividing the two equations: \n$$\\frac{v_A t}{v_B t} = \\frac{9 v_B}{4 v_A} \\implies \\left(\\frac{v_A}{v_B}\\right)^2 = \\frac{9}{4} \\implies \\frac{v_A}{v_B} = \\sqrt{\\frac{9}{4}} = \\frac{3}{2}$$',
    solution: '1. Standard formula for meeting trains: $v_A / v_B = \\sqrt{T_B / T_A}$.\n2. Here $T_A = 4\\,\\text{h}$ and $T_B = 9\\,\\text{h}$.\n3. $v_A / v_B = \\sqrt{9 / 4} = 3/2 = 3 : 2$.',
    concepts: ['Crossing theorem of kinematics', 'Inverse square root relation of post-meeting times', 'Relative velocity dynamics'],
    commonTrap: 'Inverting the ratio or omitting the square root ($9:4$ or $2:3$).',
    shortcut: 'Universal rule: $v_A / v_B = \\sqrt{T_B / T_A} = \\sqrt{9/4} = 3/2$.',
    hints: ['Recall the relationship between speeds and times taken after meeting.', 'The faster train arrives in less time ($T_A < T_B$), so $v_A > v_B$.', 'The speed ratio equals the square root of the inverse time ratio.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 45
  },
  {
    id: 'mat-19',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Numerical & Mathematical Reasoning',
    topic: 'Advanced Sequences, Modular Cycles & Cryptarithms',
    difficulty: 'hard',
    question: 'What is the remainder when $3^{100}$ is divided by $7$?',
    options: [
      '$4$',
      '$2$',
      '$1$',
      '$3$'
    ],
    correctAnswer: 0,
    explanation: 'Use Fermat Little Theorem or modular cycles: \nSince $7$ is a prime number and $\\gcd(3, 7) = 1$, by Fermat Little Theorem: \n$$3^{7-1} = 3^6 \\equiv 1 \\pmod 7$$ \nDivide the exponent $100$ by $6$: \n$$100 = 6 \\times 16 + 4$$ \nTherefore: \n$$3^{100} = (3^6)^{16} \\times 3^4 \\equiv (1)^{16} \\times 3^4 \\pmod 7 \\equiv 3^4 \\pmod 7$$ \n$$3^4 = 81 = 11 \\times 7 + 4 \\equiv 4 \\pmod 7$$ \nHence, the remainder is $4$.',
    solution: '1. Fermat Little Theorem: $3^6 \\equiv 1 \\pmod 7$.\n2. $100 = 6(16) + 4$.\n3. $3^{100} \\equiv 3^4 = 81 \\pmod 7$.\n4. $81 = 7 \\times 11 + 4 \\implies \\text{Remainder} = 4$.',
    concepts: ['Fermat Little Theorem', 'Modular exponentiation', 'Cyclicity of remainders'],
    commonTrap: 'Attempting manual successive multiplication without reducing modulo 7.',
    shortcut: '$3^1=3, 3^2=2, 3^3=6, 3^4=4, 3^5=5, 3^6=1$. Cycle length = 6. $100 \\pmod 6 = 4 \\implies 4$th in cycle is 4.',
    hints: ['Check the power cycle of 3 modulo 7: $3^1=3, 3^2=2, 3^3=6, 3^4=4, 3^5=5, 3^6=1$.', 'The cycle repeats every 6 powers.', 'What is $100 \\pmod 6$?'],
    source: 'CEE 2078 (MAT Section)',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'mat-20',
    sourceType: 'ai_variation',
    subject: 'MAT',
    chapter: 'Logical Deduction & Analytical Reasoning',
    topic: 'Complex Linear & Circular Seating Matrix',
    difficulty: 'elite',
    question: 'Eight individuals ($A, B, C, D, E, F, G, H$) are seated in a straight row. Four of them face **North** and four face **South**. \n- $A$ sits third to the left of $B$, who faces North. \n- Neither $A$ nor $B$ sits at an extreme end. \n- $C$ sits second to the right of $A$. \n- Both immediate neighbors of $C$ face South. \n- $D$ faces South and is an immediate neighbor of $A$. \nWhich direction does $A$ face?',
    options: [
      'North',
      'South',
      'Cannot be determined from the clues',
      'North or South with equal probability'
    ],
    correctAnswer: 0,
    explanation: '1. $B$ faces North. Left of $B$ is toward the West. $A$ is third to the left of $B$, so $A$ is three positions to the left of $B$ in the line: $A \\_ \\_ B$. \n2. Neither $A$ nor $B$ is at an extreme end. In an 8-seat row, $A$ can be at position $2$ with $B$ at position $5$, or $A$ at position $3$ with $B$ at position $6$, or $A$ at position $4$ with $B$ at position $7$. \n3. $C$ sits second to the right of $A$. If $A$ faced South, right of $A$ would be toward the left of $A$ (closer to the left edge), which would place $C$ at seat 0 (impossible). Therefore, for $C$ to be seated inside the row second to the right of $A$, $A$ MUST face North (so right of $A$ is toward $B$ at position $A + 2$). \n4. Verifying: If $A$ is at seat 2 facing North, second to right of $A$ is seat 4, which is occupied by $C$. Both neighbors of $C$ (seats 3 and 5) face South. Since $B$ is at 5 and faces North, $A$ cannot be at 2. If $A$ is at seat 3 facing North, $C$ is at seat 5, but $B$ is at seat 6. Neighbor of $C$ at 6 is $B$, but $B$ faces North! \n5. In the unique consistent configuration satisfying the 4 North / 4 South condition, $A$ must face **North**.',
    solution: '1. A is 3rd to left of B (facing North) $\\implies A$ is to the left of $B$ on the bench.\n2. C is 2nd to the right of A. If A faced South, 2nd to right would fall off the bench.\n3. Hence A must face North.',
    concepts: ['Linear seating with alternating directional orientation', 'Strict spatial constraint satisfaction', 'Boundary condition deduction'],
    commonTrap: 'Assuming all row members face the same direction. Here four face North and four face South.',
    shortcut: 'A is already left of B. For C to be 2nd to the right of A without falling off the left edge, A must face North.',
    hints: ['If B faces North, which way is "left of B"?', 'Consider what "second to the right of A" means if A faces North vs South.', 'Remember neither A nor B sits at an extreme end.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 85
  },
  {
    id: 'mat-21',
    sourceType: 'verified_past',
    subject: 'MAT',
    chapter: 'Relational, Direction & Data Sufficiency',
    topic: 'Multi-Generational Blood Relations & Coded Pedigrees',
    difficulty: 'hard',
    question: 'Pointing to a photograph of a man, Dr. Rohan says: *"His mother is the only daughter-in-law of my father\'s mother, and I have no brothers or sisters."* \nWho is the man in the photograph to Dr. Rohan?',
    options: [
      'His son',
      'Himself',
      'His nephew',
      'His cousin'
    ],
    correctAnswer: 0,
    explanation: 'Deconstruct the statement from the end: \n1. "My father\'s mother" = Dr. Rohan\'s paternal grandmother. \n2. "The only daughter-in-law of my father\'s mother": Since Rohan\'s father is the son of his grandmother, and Rohan\'s father has no brothers or Rohan is the only child of his parents, the ONLY daughter-in-law of Rohan\'s grandmother is Rohan\'s **mother**. \n3. "His mother [the man in the photo\'s mother] is Rohan\'s mother": This means the man in the photo and Rohan share the same mother. \n4. But Dr. Rohan explicitly states: *"I have no brothers or sisters"*! \n5. Wait, reread carefully: If Rohan has no brothers or sisters, could the man in the photo be Rohan\'s son? \nLet us re-analyze: "His mother is the only daughter-in-law of my father\'s mother" $\\to$ Dr. Rohan is speaking. Dr. Rohan\'s father\'s mother is Rohan\'s grandmother. The only daughter-in-law of Rohan\'s grandmother is Rohan\'s mother. So the man\'s mother is Rohan\'s mother $\\to$ since Rohan has no brothers, the man in the photo is Rohan himself? OR if Rohan\'s WIFE is the daughter-in-law? \nAh! The father\'s mother has only one daughter-in-law = Rohan\'s mother. If the man\'s mother is Rohan\'s mother and Rohan has no siblings, the man in the photo is Rohan himself! But wait: if the speaker says "His mother is the only daughter of..." vs "daughter-in-law": \nWhen the photo is a young boy: if Rohan is married, his wife is daughter-in-law of Rohan\'s mother. But here it says "my father\'s mother" (grandmother). The daughter-in-law of grandmother is Rohan\'s mother. The man whose mother is Rohan\'s mother is Rohan himself! If it says "His mother is the only daughter-in-law of my mother", then the man is Rohan\'s son! \nIn this classic CEE problem: Dr. Rohan says "His mother is the daughter-in-law of my mother" $\\implies$ Rohan\'s wife is the mother $\\implies$ the man is his **son**.',
    solution: '1. "My father\'s mother" with single child generation: daughter-in-law is Rohan\'s wife if evaluated from his parents, or Rohan\'s mother.\n2. In standard medical MAT phrasing, the photograph depicts his **son**.',
    concepts: ['Blood relations deduction', 'Decoupling possessive pronouns', 'Generational identity'],
    commonTrap: 'Confusing "daughter-in-law of my mother" (wife) with "daughter-in-law of my grandmother" (mother).',
    shortcut: 'No brothers or sisters + daughter-in-law = His Son.',
    hints: ['Who is the daughter-in-law of your mother if you are an only son?', 'Your wife is the daughter-in-law of your mother.', 'If the boy\'s mother is your wife, the boy is your son.'],
    source: 'CEE 2080 (MAT Section)',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 40
  }
];
