import { Question } from '@/types';

export const PHYSICS_QUESTIONS: Question[] = [
  {
    id: 'phy-01',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Electrostatics & Capacitance',
    topic: 'Capacitance & Dielectrics',
    difficulty: 'hard',
    question: 'A parallel plate capacitor is charged by a battery of EMF $V_0$ and then disconnected from the source. A dielectric slab of dielectric constant $K = 4$ is now introduced completely filling the space between the plates. If the initial electrostatic energy stored was $U_0$, the work done by the electrostatic field in pulling the dielectric into the capacitor is:',
    options: [
      '$\\frac{3}{4} U_0$',
      '$\\frac{1}{4} U_0$',
      '$3 U_0$',
      '$-3 U_0$'
    ],
    correctAnswer: 0,
    explanation: 'Since battery is disconnected, charge $Q_0$ is conserved. Initial energy $U_0 = \\frac{Q_0^2}{2C_0}$. With dielectric $K=4$, $C = 4C_0$, so final energy $U_f = \\frac{Q_0^2}{8C_0} = \\frac{U_0}{4}$. Work done by the conservative electric field is $W_{\\text{field}} = -\\Delta U = -(U_f - U_0) = -(\\frac{U_0}{4} - U_0) = +\\frac{3}{4}U_0$.',
    solution: '1. Charge conserved: $Q = Q_0$.\n2. $U_0 = Q_0^2/(2C_0)$, $U_f = Q_0^2/(2 \\cdot 4C_0) = U_0/4$.\n3. $W_{\\text{field}} = -\\Delta U = U_0 - U_f = \\frac{3}{4}U_0$.',
    concepts: ['Charge conservation', 'Capacitor energy', 'Work-energy theorem in electrostatics'],
    commonTrap: 'Confusing battery connected ($V$ constant) with disconnected ($Q$ constant).',
    shortcut: 'Disconnected slab insertion: $W_{\\text{field}} = U_0(1 - 1/K) = U_0(1 - 1/4) = \\frac{3}{4}U_0$.',
    hints: ['Identify what is constant: battery was disconnected, so charge Q is isolated.', 'Express energy in terms of Q: $U = Q^2/(2C)$.', 'Work done by field equals the decrease in stored potential energy.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'phy-02',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Electrostatics & Capacitance',
    topic: 'Capacitance & Dielectrics',
    difficulty: 'very_hard',
    originalPastQuestionId: 'phy-01',
    question: 'A parallel plate capacitor ($C_0$, area $A$, plate gap $d$) is connected to a constant voltage battery $V_0$. Two slabs of thicknesses $d/3$ and $2d/3$ with dielectric constants $K_1 = 3$ and $K_2 = 6$ are inserted to fill the entire gap while the battery **remains connected**. The net heat dissipated in the circuit during the insertion process is:',
    options: [
      '$\\frac{1}{2} C_0 V_0^2$',
      '$C_0 V_0^2$',
      '$\\frac{3}{2} C_0 V_0^2$',
      '$2 C_0 V_0^2$'
    ],
    correctAnswer: 1,
    explanation: 'Equivalent capacitance: $\\frac{1}{C_{eq}} = \\frac{d/3}{K_1 \\varepsilon_0 A} + \\frac{2d/3}{K_2 \\varepsilon_0 A} = \\frac{d}{9 \\varepsilon_0 A} + \\frac{2d}{18 \\varepsilon_0 A} = \\frac{2d}{9 \\varepsilon_0 A} \\implies C_{eq} = \\frac{9}{2} C_0 = 4.5 C_0$. Battery work $W_b = \\Delta Q \\cdot V_0 = (C_{eq} - C_0)V_0^2 = 3.5 C_0 V_0^2$. Change in stored energy $\\Delta U = \\frac{1}{2} \\Delta C V_0^2 = 1.75 C_0 V_0^2$. Heat dissipated plus mechanical work equals $W_b - \\Delta U = 1.75 C_0 V_0^2$. When slabs are inserted quasi-statically without mechanical restraint, heat dissipated in the leads equals $\\frac{1}{2} \\Delta C V_0^2 - W_{mech} = C_0 V_0^2$.',
    solution: '1. $C_{eq} = \\varepsilon_0 A / ( (d/3)/3 + (2d/3)/6 ) = \\varepsilon_0 A / (d/9 + d/9) = 4.5 C_0$.\n2. $\\Delta C = 3.5 C_0$.\n3. Heat generated in resistive leads during charging: $H = \\frac{1}{2} \\Delta C V_0^2 = C_0 V_0^2$ under restrained insertion.',
    concepts: ['Series dielectric slabs', 'Battery work', 'Energy dissipation in charging'],
    commonTrap: 'Ignoring the unequal slab thicknesses when calculating series equivalent capacitance.',
    shortcut: 'Sum series effective separations: $\\sum d_i/K_i = d/9 + d/9 = 2d/9$. Thus $C_{eq} = 4.5 C_0$.',
    hints: ['Model the composite dielectric as two capacitors in series.', 'Use $C = \\varepsilon_0 A / \\sum (d_i / K_i)$.', 'Energy supplied by battery is $\\Delta Q \\cdot V_0$.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 90
  },
  {
    id: 'phy-03',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Modern Physics & Nuclear',
    topic: 'Photoelectric Effect & Photons',
    difficulty: 'hard',
    question: 'When light of frequency $\\nu$ is incident on a photosensitive metal, stopping potential is $V_1$. When light of frequency $2\\nu$ is incident on the same metal, stopping potential is $V_2 = 2.5 V_1$. The work function of the metal is:',
    options: [
      '$\\frac{1}{3} h\\nu$',
      '$\\frac{2}{3} h\\nu$',
      '$\\frac{1}{2} h\\nu$',
      '$\\frac{3}{5} h\\nu$'
    ],
    correctAnswer: 0,
    explanation: 'Einstein photoelectric equations: (1) $e V_1 = h\\nu - \\phi$, (2) $e V_2 = 2.5 e V_1 = 2h\\nu - \\phi$. Multiply (1) by 2.5: $2.5 e V_1 = 2.5 h\\nu - 2.5 \\phi$. Equating: $2.5 h\\nu - 2.5 \\phi = 2h\\nu - \\phi \\implies 0.5 h\\nu = 1.5 \\phi \\implies \\phi = \\frac{0.5}{1.5} h\\nu = \\frac{1}{3} h\\nu$.',
    solution: '1. $e V_1 = h\\nu - \\phi$.\n2. $2.5 e V_1 = 2h\\nu - \\phi$.\n3. $2.5(h\\nu - \\phi) = 2h\\nu - \\phi \\implies 0.5 h\\nu = 1.5 \\phi \\implies \\phi = \\frac{1}{3} h\\nu$.',
    concepts: ['Einstein photoelectric equation', 'Stopping potential', 'Work function'],
    commonTrap: 'Failing to eliminate stopping potential properly or sign error on work function.',
    shortcut: 'Ratio $V_2/V_1 = (2h\\nu - \\phi)/(h\\nu - \\phi) = 2.5 \\implies 2.5(h\\nu - \\phi) = 2h\\nu - \\phi \\implies \\phi = h\\nu / 3$.',
    hints: ['Write the photoelectric equation for both frequencies.', 'Set up the ratio $V_2 / V_1 = 2.5$.', 'Cross-multiply to isolate $\\phi$ in terms of $h\\nu$.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 60
  },
  {
    id: 'phy-04',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Current Electricity & Circuits',
    topic: 'Potentiometer & Meter Bridge',
    difficulty: 'hard',
    question: 'A potentiometer wire of length $100\\,\\text{cm}$ has resistance $10\\,\\Omega$. It is connected in series with a cell of EMF $2\\,\\text{V}$, negligible internal resistance, and a series resistance $R$. A balancing length of $40\\,\\text{cm}$ is obtained for a cell of EMF $10\\,\\text{mV}$. The value of series resistance $R$ is:',
    options: [
      '$790\\,\\Omega$',
      '$7990\\,\\Omega$',
      '$390\\,\\Omega$',
      '$4990\\,\\Omega$'
    ],
    correctAnswer: 1,
    explanation: 'Potential gradient required: $k = \\frac{E}{l} = \\frac{10 \\times 10^{-3}\\,\\text{V}}{40\\,\\text{cm}} = 2.5 \\times 10^{-4}\\,\\text{V/cm} = 0.025\\,\\text{V/m}$. For total wire length $L = 100\\,\\text{cm} = 1\\,\\text{m}$, voltage drop across wire $V_w = k \\times 100\\,\\text{cm} = 0.025\\,\\text{V}$. Current in potentiometer wire $I = \\frac{V_w}{R_w} = \\frac{0.025\\,\\text{V}}{10\\,\\Omega} = 2.5 \\times 10^{-3}\\,\\text{A}$. Driver circuit EMF is $2\\,\\text{V}$, so total circuit resistance $R_{total} = \\frac{2\\,\\text{V}}{2.5 \\times 10^{-3}\\,\\text{A}} = 800\\,\\Omega$. Since $R_w = 10\\,\\Omega$, series resistance $R = 800 - 10 = 790\\,\\Omega$.',
    solution: '1. $k = 10\\,\\text{mV} / 40\\,\\text{cm} = 0.25\\,\\text{mV/cm}$.\n2. $V_w = k \\times 100\\,\\text{cm} = 25\\,\\text{mV} = 0.025\\,\\text{V}$.\n3. $I = 0.025 / 10 = 2.5 \\times 10^{-3}\\,\\text{A}$.\n4. $R + 10 = 2 / (2.5 \\times 10^{-3}) = 800\\,\\Omega \\implies R = 790\\,\\Omega$.',
    concepts: ['Potentiometer balance condition', 'Potential gradient', 'Ohm law in divider circuits'],
    commonTrap: 'Forgetting to subtract wire resistance $R_w = 10\\,\\Omega$ from total circuit resistance $800\\,\\Omega$.',
    shortcut: '$R = \\frac{E_{driver}}{V_{cell}} \\cdot \\frac{l_{bal}}{L} \\cdot R_w - R_w = \\frac{2}{0.010} \\cdot \\frac{40}{100} \\cdot 10 - 10 = 800 - 10 = 790\\,\\Omega$.',
    hints: ['Find the potential gradient $k = E_{test} / l_{balance}$.', 'Calculate total voltage drop across the entire $100\\,\\text{cm}$ wire.', 'Find total current and solve for series resistance $R$.'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 70
  },
  {
    id: 'phy-05',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Current Electricity & Circuits',
    topic: 'Kirchhoff Laws & Circuit Networks',
    difficulty: 'elite',
    question: 'Twelve identical resistors, each of resistance $R$, form the edges of a cube. A battery of EMF $\\mathcal{E}$ with zero internal resistance is connected across the **face diagonal** of the cube (between nodes at opposite corners of one square face). The equivalent resistance of the network across this face diagonal is:',
    options: [
      '$\\frac{5}{6} R$',
      '$\\frac{3}{4} R$',
      '$\\frac{7}{12} R$',
      '$\\frac{4}{3} R$'
    ],
    correctAnswer: 1,
    explanation: 'By planar symmetry with respect to the plane bisecting the face diagonal: nodes on the opposite face lie at symmetric equipotentials. Exploiting the nodal symmetry across the face diagonal leads to current division: $I_{in} = 2I_1 + I_2$. Resolving loop equations yields total voltage drop $V = \\frac{3}{4} I R$, giving equivalent resistance $R_{eq} = \\frac{3}{4} R$.',
    solution: '1. Standard cube resistances:\n   - Body diagonal: $R_{body} = \\frac{5}{6}R$.\n   - Face diagonal: $R_{face} = \\frac{3}{4}R$.\n   - Edge adjacent: $R_{edge} = \\frac{7}{12}R$.\n2. Across the face diagonal, $R_{eq} = \\frac{3}{4}R$.',
    concepts: ['Symmetry in 3D resistor networks', 'Equipotential folding', 'Nodal analysis'],
    commonTrap: 'Confusing body diagonal ($5/6 R$) with face diagonal ($3/4 R$) and edge ($7/12 R$).',
    shortcut: 'Remember the classic CEE cube trilogy: Edge = $7/12 R$, Face = $3/4 R$ ($9/12 R$), Body = $5/6 R$ ($10/12 R$).',
    hints: ['Notice that this is connected across a FACE diagonal, not the body diagonal.', 'Identify equipotential nodes that can be joined without altering currents.', 'Recall the standard cube symmetries: $7/12 R, 3/4 R, 5/6 R$.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 80
  },
  {
    id: 'phy-06',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Thermodynamics & Heat',
    topic: 'First & Second Laws & Carnot Engine',
    difficulty: 'hard',
    question: 'A reversible Carnot engine operates between temperatures $T_1$ and $T_2$ ($T_1 > T_2$) with efficiency $\\eta = 0.40$. When the source temperature $T_1$ is kept unchanged and the sink temperature $T_2$ is reduced by $50\\,\\text{K}$, its efficiency increases to $0.50$. The temperature of the source $T_1$ is:',
    options: [
      '$500\\,\\text{K}$',
      '$600\\,\\text{K}$',
      '$400\\,\\text{K}$',
      '$300\\,\\text{K}$'
    ],
    correctAnswer: 0,
    explanation: 'Efficiency $\\eta = 1 - \\frac{T_2}{T_1}$. Given $\\eta_1 = 0.40 \\implies \\frac{T_2}{T_1} = 0.60$. For the new state: $\\eta_2 = 1 - \\frac{T_2 - 50}{T_1} = 0.50 \\implies \\frac{T_2 - 50}{T_1} = 0.50$. Subtracting: $\\frac{T_2}{T_1} - \\frac{T_2 - 50}{T_1} = 0.60 - 0.50 \\implies \\frac{50}{T_1} = 0.10 \\implies T_1 = \\frac{50}{0.10} = 500\\,\\text{K}$.',
    solution: '1. $1 - T_2/T_1 = 0.40 \\implies T_2/T_1 = 0.60$.\n2. $1 - (T_2-50)/T_1 = 0.50 \\implies (T_2-50)/T_1 = 0.50$.\n3. $T_2/T_1 - (T_2-50)/T_1 = 50/T_1 = 0.10$.\n4. $T_1 = 500\\,\\text{K}$.',
    concepts: ['Carnot engine efficiency', 'Absolute temperature scale', 'Second law of thermodynamics'],
    commonTrap: 'Using Celsius instead of absolute Kelvin temperatures.',
    shortcut: '$\\Delta \\eta = \\frac{\\Delta T_{sink}}{T_1} \\implies 0.10 = \\frac{50}{T_1} \\implies T_1 = 500\\,\\text{K}$.',
    hints: ['Write the expression for $\\eta$ in both cases: $\\eta = 1 - T_2/T_1$.', 'Notice that $\\Delta \\eta = \\Delta T_2 / T_1$.', 'Solve directly for source temperature $T_1$.'],
    source: 'CEE 2077',
    year: 2077,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-07',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Thermodynamics & Heat',
    topic: 'First & Second Laws & Carnot Engine',
    difficulty: 'very_hard',
    question: 'One mole of an ideal monoatomic gas ($\\gamma = 5/3$) undergoes a polytropic process $P V^2 = \\text{constant}$. The molar heat capacity $C$ of the gas during this process is:',
    options: [
      '$\\frac{1}{2} R$',
      '$\\frac{5}{2} R$',
      '$-R$',
      '$\\frac{3}{2} R$'
    ],
    correctAnswer: 0,
    explanation: 'For any polytropic process $P V^n = \\text{constant}$, the molar heat capacity is given by $C = C_v + \\frac{R}{1 - n}$. For a monoatomic gas, $C_v = \\frac{3}{2} R$. Here the polytropic index $n = 2$. Therefore, $C = \\frac{3}{2} R + \\frac{R}{1 - 2} = \\frac{3}{2} R - R = \\frac{1}{2} R$.',
    solution: '1. Polytropic formula: $C = C_v + \\frac{R}{1-n}$.\n2. Monoatomic gas: $C_v = \\frac{3}{2}R$.\n3. Here $n = 2$.\n4. $C = \\frac{3}{2}R + \\frac{R}{1-2} = \\frac{3}{2}R - R = \\frac{1}{2}R$.',
    concepts: ['Polytropic process', 'Molar heat capacity', 'First law differential analysis'],
    commonTrap: 'Using $R/(n-1)$ with a wrong sign. The standard formula is $C = C_v + R/(1-n)$.',
    shortcut: 'Monoatomic: $C_v = 1.5R$. $n=2 \\implies R/(1-2) = -R$. $C = 1.5R - R = 0.5R$.',
    hints: ['Recall the general polytropic formula: $C = C_v + R/(1-n)$.', 'For a monoatomic gas, what is $C_v$ in terms of $R$?', 'Substitute $n = 2$ and evaluate.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'phy-08',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Mechanics & Rotational Motion',
    topic: 'Rotational Dynamics & Moment of Inertia',
    difficulty: 'hard',
    question: 'A solid cylinder, a solid sphere, and a thin hollow sphere of identical masses and radii are released simultaneously from the top of an inclined plane and roll down without slipping. The order in which they reach the bottom of the incline is:',
    options: [
      'Solid sphere, solid cylinder, hollow sphere',
      'Solid cylinder, solid sphere, hollow sphere',
      'Hollow sphere, solid sphere, solid cylinder',
      'All reach simultaneously'
    ],
    correctAnswer: 0,
    explanation: 'Acceleration of rolling without slipping on an incline: $a = \\frac{g \\sin\\theta}{1 + k^2/R^2}$, where $k^2/R^2 = I / (mR^2)$. For solid sphere: $k^2/R^2 = 2/5 = 0.40 \\implies a = g\\sin\\theta / 1.40 = 0.714 g\\sin\\theta$. For solid cylinder: $k^2/R^2 = 1/2 = 0.50 \\implies a = g\\sin\\theta / 1.50 = 0.667 g\\sin\\theta$. For hollow sphere: $k^2/R^2 = 2/3 = 0.667 \\implies a = g\\sin\\theta / 1.667 = 0.600 g\\sin\\theta$. Highest acceleration reaches first: Solid sphere > Solid cylinder > Hollow sphere.',
    solution: '1. $a = g \\sin\\theta / (1 + I/mR^2)$.\n2. Solid sphere: $I/(mR^2) = 0.4$ (highest acceleration, reaches first).\n3. Solid cylinder: $I/(mR^2) = 0.5$ (second).\n4. Hollow sphere: $I/(mR^2) = 0.67$ (lowest acceleration, reaches last).',
    concepts: ['Pure rolling down incline', 'Moment of inertia fraction $k^2/R^2$', 'Rotational acceleration'],
    commonTrap: 'Thinking that mass or radius affects the arrival time. Only the geometric distribution of mass ($k^2/R^2$) determines pure rolling acceleration.',
    shortcut: 'Smallest $I/(mR^2)$ rolls fastest. $2/5 (0.4) < 1/2 (0.5) < 2/3 (0.67)$.',
    hints: ['Write the acceleration formula for pure rolling on an inclined plane.', 'Identify $I / (mR^2)$ for each of the three shapes.', 'The shape with the lowest fractional inertia has the highest linear acceleration.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-09',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Mechanics & Rotational Motion',
    topic: 'Rotational Dynamics & Moment of Inertia',
    difficulty: 'elite',
    question: 'A uniform solid sphere of mass $M$ and radius $R$ is placed on a rough horizontal surface and given an initial purely horizontal velocity $v_0$ with **zero initial angular velocity** ($\\omega_0 = 0$). The coefficient of kinetic friction with the floor is $\\mu_k$. The distance traveled by the sphere before it begins rolling without slipping is:',
    options: [
      '$\\frac{2 v_0^2}{49 \\mu_k g}$',
      '$\\frac{12 v_0^2}{49 \\mu_k g}$',
      '$\\frac{2 v_0^2}{7 \\mu_k g}$',
      '$\\frac{10 v_0^2}{49 \\mu_k g}$'
    ],
    correctAnswer: 1,
    explanation: 'Friction $f_k = \\mu_k M g$ opposes motion, causing deceleration $a = \\mu_k g$. Torque about center: $\\tau = f_k R = I \\alpha \\implies \\mu_k M g R = (\\frac{2}{5} M R^2) \\alpha \\implies \\alpha = \\frac{5 \\mu_k g}{2R}$. Pure rolling sets in when $v(t) = R \\omega(t)$. Here $v(t) = v_0 - \\mu_k g t$ and $\\omega(t) = \\alpha t = \\frac{5 \\mu_k g}{2R} t$. Equating: $v_0 - \\mu_k g t = \\frac{5}{2} \\mu_k g t \\implies \\frac{7}{2} \\mu_k g t = v_0 \\implies t_0 = \\frac{2 v_0}{7 \\mu_k g}$. Distance $s = v_0 t_0 - \\frac{1}{2} a t_0^2 = v_0 (\\frac{2v_0}{7\\mu_k g}) - \\frac{1}{2} (\\mu_k g) (\\frac{4 v_0^2}{49 \\mu_k^2 g^2}) = \\frac{2 v_0^2}{7\\mu_k g} - \\frac{2 v_0^2}{49\\mu_k g} = \\frac{14 - 2}{49} \\frac{v_0^2}{\\mu_k g} = \\frac{12 v_0^2}{49 \\mu_k g}$.',
    solution: '1. Linear deceleration: $a = \\mu_k g \\implies v(t) = v_0 - \\mu_k g t$.\n2. Angular acceleration: $\\alpha = \\frac{\\mu_k M g R}{\\frac{2}{5} M R^2} = \\frac{5 \\mu_k g}{2R} \\implies \\omega(t) = \\frac{5 \\mu_k g}{2R} t$.\n3. Rolling condition: $v(t) = R \\omega(t) \\implies t = \\frac{2v_0}{7 \\mu_k g}$.\n4. Distance: $s = v_0 t - \\frac{1}{2} a t^2 = \\frac{12 v_0^2}{49 \\mu_k g}$.',
    concepts: ['Transition from sliding to pure rolling', 'Angular momentum conservation about contact line', 'Work done by friction'],
    commonTrap: 'Using $v^2 = u^2 - 2as$ with $v=0$. The final velocity is NOT zero; it is rolling with speed $v = \\frac{5}{7} v_0$.',
    shortcut: 'Final rolling speed is $v = \\frac{5}{7} v_0$. Using $v^2 - v_0^2 = -2as \\implies (\\frac{25}{49} - 1) v_0^2 = -2 (\\mu_k g) s \\implies s = \\frac{12 v_0^2}{49 \\mu_k g}$.',
    hints: ['Find the time when $v(t) = R \\omega(t)$.', 'Remember angular acceleration comes from kinetic friction torque about the center.', 'Calculate distance using $s = v_0 t - \\frac{1}{2} a t^2$ or work-energy.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 110
  },
  {
    id: 'phy-10',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Optics',
    topic: 'Wave Optics & Interference (YDSE)',
    difficulty: 'hard',
    question: 'In Young double-slit experiment, the intensity at the central maximum is $I_0$. When a thin transparent mica sheet of thickness $t = 1.2\\,\\mu\\text{m}$ and refractive index $\\mu = 1.5$ is introduced in front of one of the slits, the optical path difference at the original central position changes. If the wavelength of light used is $\\lambda = 600\\,\\text{nm}$, the intensity at the original central position becomes:',
    options: [
      '$I_0$',
      '$0$',
      '$\\frac{I_0}{2}$',
      '$\\frac{I_0}{4}$',
    ],
    correctAnswer: 0,
    explanation: 'Optical path difference introduced by the sheet: $\\Delta x = (\\mu - 1)t = (1.5 - 1)(1.2 \\times 10^{-6}\\,\\text{m}) = 0.5 \\times 1.2 \\times 10^{-6}\\,\\text{m} = 0.6 \\times 10^{-6}\\,\\text{m} = 600\\,\\text{nm}$. Since $\\Delta x = 600\\,\\text{nm} = 1\\lambda$, the path difference is an integral multiple of $\\lambda$ ($n = 1$). Corresponding phase difference $\\phi = \\frac{2\\pi}{\\lambda} \\Delta x = 2\\pi$. Resultant intensity $I = I_0 \\cos^2(\\phi/2) = I_0 \\cos^2(\\pi) = I_0 ( -1 )^2 = I_0$.',
    solution: '1. Path difference: $\\Delta x = (\\mu - 1)t = (0.5)(1200\\,\\text{nm}) = 600\\,\\text{nm}$.\n2. Given $\\lambda = 600\\,\\text{nm} \\implies \\Delta x = 1\\lambda$.\n3. Phase difference $\\phi = 2\\pi$.\n4. Intensity $I = I_0 \\cos^2(\\phi/2) = I_0 \\cos^2(\\pi) = I_0$.',
    concepts: ['Optical path difference of thin sheet', 'YDSE fringe shift', 'Interference intensity distribution'],
    commonTrap: 'Thinking any introduced sheet destroys the central maximum intensity. When path shift equals an integer number of wavelengths ($n\\lambda$), constructive interference is preserved.',
    shortcut: '$\\Delta x = 0.5 \\times 1200\\,\\text{nm} = 600\\,\\text{nm} = 1\\lambda$. Integral multiple of $\\lambda$ always gives maximum intensity $I_0$.',
    hints: ['Calculate the optical path difference introduced: $\\Delta x = (\\mu - 1)t$.', 'Compare $\\Delta x$ with the given wavelength $\\lambda = 600\\,\\text{nm}$.', 'What is the interference condition when path difference is an integer multiple of $\\lambda$?'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-11',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Modern Physics & Nuclear',
    topic: 'Nuclear Physics & Radioactivity',
    difficulty: 'hard',
    question: 'A radioactive sample contains two radioactive nuclei $A$ and $B$. Initially, number of nuclei of $A$ is four times that of $B$. The half-life of $A$ is $20\\,\\text{minutes}$ and that of $B$ is $40\\,\\text{minutes}$. After what time will the number of nuclei of $A$ and $B$ become equal?',
    options: [
      '$40\\,\\text{minutes}$',
      '$60\\,\\text{minutes}$',
      '$80\\,\\text{minutes}$',
      '$120\\,\\text{minutes}$'
    ],
    correctAnswer: 2,
    explanation: 'Number of remaining nuclei: $N_A(t) = N_{A0} (1/2)^{t/T_A}$ and $N_B(t) = N_{B0} (1/2)^{t/T_B}$. Given $N_{A0} = 4 N_{B0}$. When $N_A(t) = N_B(t)$: $4 N_{B0} (1/2)^{t/20} = N_{B0} (1/2)^{t/40} \\implies 4 = \\frac{(1/2)^{t/40}}{(1/2)^{t/20}} = (1/2)^{t/40 - t/20} = (1/2)^{-t/40} = 2^{t/40}$. Since $4 = 2^2$, we have $2^{t/40} = 2^2 \\implies \\frac{t}{40} = 2 \\implies t = 80\\,\\text{minutes}$.',
    solution: '1. $N_A(t) = 4 N_{B0} \\cdot 2^{-t/20}$.\n2. $N_B(t) = N_{B0} \\cdot 2^{-t/40}$.\n3. Equating: $4 \\cdot 2^{-t/20} = 2^{-t/40} \\implies 2^2 = 2^{t/20 - t/40} = 2^{t/40}$.\n4. $t/40 = 2 \\implies t = 80\\,\\text{min}$.',
    concepts: ['Radioactive decay law', 'Half-life relations', 'Exponential decay curves'],
    commonTrap: 'Trying to average the half-lives ($20 + 40 = 60$).',
    shortcut: '$N_A/N_B = (N_{A0}/N_{B0}) \\cdot 2^{-t(1/T_A - 1/T_B)} = 1 \\implies 4 = 2^{t(1/20 - 1/40)} = 2^{t/40} \\implies t = 80\\,\\text{min}$.',
    hints: ['Set up the decay equations for $A$ and $B$ using powers of $1/2$ or $2$.', 'Use the given initial ratio $N_{A0} / N_{B0} = 4 = 2^2$.', 'Equate the two exponents and solve for $t$.'],
    source: 'MECEE-BL 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 55
  },
  {
    id: 'phy-12',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Modern Physics & Nuclear',
    topic: 'Nuclear Physics & Radioactivity',
    difficulty: 'very_hard',
    question: 'A radionuclide $X$ decays into a stable isotope $Y$ via $\\beta^-$ emission with a decay constant $\\lambda$. At $t = 0$, a sample contains pure $X$. The ratio of the number of daughter nuclei $N_Y$ to parent nuclei $N_X$ becomes equal to $7$ at time $t$ equal to:',
    options: [
      '$\\frac{3 \\ln 2}{\\lambda}$',
      '$\\frac{7 \\ln 2}{\\lambda}$',
      '$\\frac{\\ln 7}{\\lambda}$',
      '$\\frac{2 \\ln 2}{\\lambda}$'
    ],
    correctAnswer: 0,
    explanation: 'Since all decayed $X$ becomes $Y$, total nuclei $N_0 = N_X(t) + N_Y(t)$. Given $N_Y / N_X = 7 \\implies N_Y = 7 N_X$. Therefore, $N_0 = N_X + 7 N_X = 8 N_X \\implies N_X(t) = \\frac{N_0}{8} = N_0 \\left(\\frac{1}{2}\\right)^3$. This means exactly 3 half-lives have elapsed. Since half-life $T_{1/2} = \\frac{\\ln 2}{\\lambda}$, time $t = 3 T_{1/2} = \\frac{3 \\ln 2}{\\lambda}$.',
    solution: '1. $N_Y / N_X = 7 \\implies N_X / N_0 = 1/8 = (1/2)^3$.\n2. Number of half-lives $n = 3$.\n3. $t = 3 T_{1/2} = 3 (\\frac{\\ln 2}{\\lambda}) = \\frac{3 \\ln 2}{\\lambda}$.',
    concepts: ['Daughter-to-parent isotope ratio', 'Half-life relation with decay constant', 'Conservation of nucleons'],
    commonTrap: 'Using $\\ln(7)/\\lambda$ instead of recognizing that $N_0 = N_X + N_Y = 8 N_X$.',
    shortcut: '$N_Y/N_X = 7 \\implies N_X/N_0 = 1/(1+7) = 1/8 = 2^{-3} \\implies 3$ half-lives $\\implies 3\\ln 2/\\lambda$.',
    hints: ['Total initial nuclei $N_0$ equals $N_X(t) + N_Y(t)$.', 'What fraction of initial parent nuclei remains when the daughter-to-parent ratio is 7?', 'Express 3 half-lives in terms of the decay constant $\\lambda$.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-13',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Current Electricity & Circuits',
    topic: 'Kirchhoff Laws & Circuit Networks',
    difficulty: 'hard',
    question: 'In the circuit below, five identical cells each of internal resistance $r = 1\\,\\Omega$ and EMF $\\mathcal{E} = 2\\,\\text{V}$ are connected in series. However, one of the cells is erroneously connected with reversed polarity. The entire combination is connected to an external resistor $R = 5\\,\\Omega$. The terminal potential difference across the reversed cell is:',
    options: [
      '$2.6\\,\\text{V}$',
      '$1.4\\,\\text{V}$',
      '$0.6\\,\\text{V}$',
      '$2.0\\,\\text{V}$'
    ],
    correctAnswer: 0,
    explanation: 'When one cell out of 5 is reversed, the net EMF becomes $(5 - 2 \\times 1)\\mathcal{E} = 3\\mathcal{E} = 3 \\times 2 = 6\\,\\text{V}$. The internal resistance is unaffected by polarity: $r_{total} = 5r = 5\\,\\Omega$. Total circuit resistance $R_{total} = R + 5r = 5 + 5 = 10\\,\\Omega$. Current in the circuit $I = \\frac{\\mathcal{E}_{net}}{R_{total}} = \\frac{6\\,\\text{V}}{10\\,\\Omega} = 0.6\\,\\text{A}$. For the reversed cell, current enters through its positive terminal (it is being charged): terminal potential difference $V = \\mathcal{E} + I r = 2 + (0.6 \\times 1) = 2.6\\,\\text{V}$.',
    solution: '1. Net EMF: $(5 - 2)\\mathcal{E} = 3(2) = 6\\,\\text{V}$.\n2. Total resistance: $R + 5r = 5 + 5 = 10\\,\\Omega$.\n3. Circuit current: $I = 6 / 10 = 0.6\\,\\text{A}$.\n4. Reversed cell is being charged: $V_{reversed} = \\mathcal{E} + I r = 2 + (0.6)(1) = 2.6\\,\\text{V}$.',
    concepts: ['Reversed cell in series', 'Charging vs discharging terminal potential', 'Ohm law in multi-cell circuits'],
    commonTrap: 'Using $V = \\mathcal{E} - I r = 1.4\\,\\text{V}$. That applies only when the cell is discharging! A reversed cell is being charged by the other cells, so $V = \\mathcal{E} + I r$.',
    shortcut: 'Reversed cell is charged $\\implies V = E + Ir > E$. Only option A ($2.6\\,\\text{V}$) is greater than $2.0\\,\\text{V}$!',
    hints: ['What is the net EMF when 1 cell out of 5 is reversed? Remember it cancels itself and one other cell.', 'Calculate circuit current $I$.', 'Is the reversed cell discharging or being charged? Use $V = \\mathcal{E} + I r$.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 65
  },
  {
    id: 'phy-14',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Modern Physics & Nuclear',
    topic: 'Bohr Model & Atomic Spectra',
    difficulty: 'hard',
    question: 'In a hydrogen-like ion of atomic number $Z$, the photon emitted during transition from $n = 3$ to $n = 1$ has wavelength $\\lambda_1$. The photon emitted during transition from $n = 2$ to $n = 1$ has wavelength $\\lambda_2$. If $\\lambda_2 / \\lambda_1 = 32 / 27$, the value of atomic number $Z$ is:',
    options: [
      'Independent of $Z$',
      '$2$',
      '$3$',
      '$4$'
    ],
    correctAnswer: 0,
    explanation: 'By Rydberg formula: $\\frac{1}{\\lambda} = R Z^2 \\left(\\frac{1}{n_f^2} - \\frac{1}{n_i^2}\\right)$. For transition $3 \\to 1$: $\\frac{1}{\\lambda_1} = R Z^2 (1 - 1/9) = R Z^2 (8/9)$. For transition $2 \\to 1$: $\\frac{1}{\\lambda_2} = R Z^2 (1 - 1/4) = R Z^2 (3/4)$. Ratio of wavelengths: $\\frac{\\lambda_2}{\\lambda_1} = \\frac{8/9}{3/4} = \\frac{8 \\times 4}{9 \\times 3} = \\frac{32}{27}$. Notice that $Z^2$ cancels out identically in the ratio! Therefore, the ratio is completely independent of $Z$.',
    solution: '1. $1/\\lambda_1 = R Z^2 (1 - 1/9) = \\frac{8}{9} R Z^2$.\n2. $1/\\lambda_2 = R Z^2 (1 - 1/4) = \\frac{3}{4} R Z^2$.\n3. $\\lambda_2 / \\lambda_1 = (8/9) / (3/4) = 32/27$.\n4. $Z$ cancels out; the relation holds for all hydrogen-like atoms.',
    concepts: ['Rydberg formula', 'Hydrogen-like transitions', 'Wavelength ratio scaling'],
    commonTrap: 'Wasting 2 minutes trying to solve for $Z$ with algebra when $Z^2$ cancels out completely in the ratio of wavelengths for the same species!',
    shortcut: 'Wavelength ratios within the same atomic species never depend on $Z$.',
    hints: ['Write the Rydberg formula for both transitions.', 'Take the ratio $\\lambda_2 / \\lambda_1$.', 'Does $Z$ survive the ratio?'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 45
  },
  {
    id: 'phy-15',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Modern Physics & Nuclear',
    topic: 'Bohr Model & Atomic Spectra',
    difficulty: 'elite',
    question: 'A hydrogen atom in its ground state absorbs a photon and gets excited to the state $n = 4$. What is the ratio of the de Broglie wavelength of the orbiting electron in the $n = 4$ state to that in the ground state ($n = 1$)?',
    options: [
      '$4 : 1$',
      '$16 : 1$',
      '$1 : 4$',
      '$2 : 1$'
    ],
    correctAnswer: 0,
    explanation: 'By Bohr quantization of angular momentum and de Broglie hypothesis: the orbital circumference satisfies $2\\pi r_n = n \\lambda_{dB}$. Orbit radius scales as $r_n = r_1 n^2$. Therefore, $2\\pi (r_1 n^2) = n \\lambda_{dB} \\implies \\lambda_{dB} = 2\\pi r_1 n$. Thus, the de Broglie wavelength of the orbiting electron is directly proportional to the principal quantum number $n$! For $n = 4$, $\\lambda_4 / \\lambda_1 = 4 / 1 = 4 : 1$.',
    solution: '1. De Broglie condition: $2\\pi r_n = n \\lambda_n$.\n2. $r_n = n^2 r_1$.\n3. $2\\pi (n^2 r_1) = n \\lambda_n \\implies \\lambda_n = n (2\\pi r_1)$.\n4. Therefore $\\lambda_4 / \\lambda_1 = 4 / 1$.',
    concepts: ['De Broglie matter waves', 'Bohr quantization of angular momentum', 'Orbital circumference scaling'],
    commonTrap: 'Confusing de Broglie wavelength of electron with photon wavelength, or thinking it scales as $n^2$ like the radius.',
    shortcut: 'Circumference = $n \\lambda \\implies n^2 \\propto n \\lambda \\implies \\lambda \\propto n$. Ratio = 4:1.',
    hints: ['Recall Bohr standing wave condition: $2\\pi r_n = n \\lambda$.', 'How does the radius $r_n$ scale with $n$?', 'Substitute $r_n \\propto n^2$ into the standing wave equation.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  },
  {
    id: 'phy-16',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Optics',
    topic: 'Ray Optics & Optical Instruments',
    difficulty: 'hard',
    question: 'A biconvex thin lens made of glass of refractive index $\\mu_g = 1.5$ has focal length $f = 20\\,\\text{cm}$ in air. When the lens is completely immersed in a liquid of refractive index $\\mu_l = 1.6$, its new focal length is:',
    options: [
      '$-160\\,\\text{cm}$',
      '$+160\\,\\text{cm}$',
      '$-80\\,\\text{cm}$',
      '$+80\\,\\text{cm}$'
    ],
    correctAnswer: 0,
    explanation: 'Lens maker formula in air: $\\frac{1}{f_a} = (\\mu_g - 1)\\left(\\frac{1}{R_1} - \\frac{1}{R_2}\\right) = (1.5 - 1) K = 0.5 K \\implies K = \\frac{1}{0.5 \\times 20} = \\frac{1}{10}$. In liquid: $\\frac{1}{f_l} = \\left(\\frac{\\mu_g}{\\mu_l} - 1\\right) K = \\left(\\frac{1.5}{1.6} - 1\\right) \\left(\\frac{1}{10}\\right) = \\left(-\\frac{0.1}{1.6}\\right)\\left(\\frac{1}{10}\\right) = -\\frac{1}{160}$. Therefore, $f_l = -160\\,\\text{cm}$. The lens becomes diverging (negative focal length) because the liquid is optically denser than the glass!',
    solution: '1. $1/f_a = (1.5 - 1) K = 0.5 K = 1/20 \\implies K = 1/10$.\n2. $1/f_l = (1.5/1.6 - 1) K = (-1/16)(1/10) = -1/160$.\n3. $f_l = -160\\,\\text{cm}$.',
    concepts: ['Lens maker formula', 'Immersion in denser optical medium', 'Convergence to divergence inversion'],
    commonTrap: 'Missing the negative sign. When immersed in a medium with refractive index greater than the lens material ($\\\\mu_l > \\mu_g$), a convex lens acts as a concave diverging lens!',
    shortcut: '$f_l / f_a = \\frac{\\mu_g - 1}{\\mu_g/\\mu_l - 1} = \\frac{0.5}{1.5/1.6 - 1} = \\frac{0.5 \\times 1.6}{-0.1} = -8 \\implies f_l = -8 \\times 20 = -160\\,\\text{cm}$.',
    hints: ['Use the lens maker formula for both air and liquid.', 'Relative refractive index in liquid is $\\mu_g / \\mu_l$.', 'Notice that $\\mu_l > \\mu_g$; what does that do to the sign of the focal length?'],
    source: 'CEE 2078',
    year: 2078,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 60
  },
  {
    id: 'phy-17',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Thermodynamics & Heat',
    topic: 'Kinetic Theory of Gases',
    difficulty: 'hard',
    question: 'The root-mean-square velocity of nitrogen molecules ($N_2$, molar mass $28\\,\\text{g/mol}$) at temperature $T_1$ equals the most probable velocity of helium atoms ($He$, molar mass $4\\,\\text{g/mol}$) at temperature $T_2$. The ratio $T_1 / T_2$ is:',
    options: [
      '$\\frac{14}{3}$',
      '$\\frac{3}{14}$',
      '$\\frac{7}{3}$',
      '$\\frac{28}{3}$'
    ],
    correctAnswer: 0,
    explanation: 'Speeds: $V_{rms} = \\sqrt{\\frac{3RT}{M}}$ and $V_{mp} = \\sqrt{\\frac{2RT}{M}}$. Given $V_{rms}(N_2) = V_{mp}(He) \\implies \\sqrt{\\frac{3 R T_1}{28}} = \\sqrt{\\frac{2 R T_2}{4}}$. Squaring both sides: $\\frac{3 T_1}{28} = \\frac{2 T_2}{4} = \\frac{T_2}{2} \\implies \\frac{T_1}{T_2} = \\frac{28}{3 \\times 2} = \\frac{14}{3}$.',
    solution: '1. $V_{rms}(N_2) = \\sqrt{3RT_1 / 28}$.\n2. $V_{mp}(He) = \\sqrt{2RT_2 / 4} = \\sqrt{RT_2 / 2}$.\n3. $3T_1 / 28 = T_2 / 2 \\implies T_1 / T_2 = 28 / 6 = 14/3$.',
    concepts: ['Vrms vs Vmp formulas', 'Molecular mass scaling', 'Kinetic theory of Maxwell-Boltzmann distribution'],
    commonTrap: 'Swapping the factors: $V_{rms}$ has 3, $V_{mp}$ has 2, $V_{avg}$ has $8/\\pi$.',
    shortcut: '$\\frac{3 T_1}{M_1} = \\frac{2 T_2}{M_2} \\implies \\frac{T_1}{T_2} = \\frac{2}{3} \\frac{M_1}{M_2} = \\frac{2}{3} \\times \\frac{28}{4} = \\frac{14}{3}$.',
    hints: ['Write the formula for $V_{rms}$ and $V_{mp}$.', 'Set their expressions equal and square both sides.', 'Solve for $T_1 / T_2$.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-18',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Electrostatics & Capacitance',
    topic: 'Electric Field & Potential',
    difficulty: 'elite',
    question: 'A uniformly charged thin spherical shell of radius $R$ carries total charge $+Q$. A point charge $-q$ ($q < Q$) is placed at a distance $r = R/2$ from the center of the shell. The net electrostatic force experienced by the shell due to the point charge is:',
    options: [
      'Zero',
      '$\\frac{1}{4\\pi\\varepsilon_0} \\frac{q Q}{R^2}$ radially inward',
      '$\\frac{1}{4\\pi\\varepsilon_0} \\frac{4 q Q}{R^2}$ radially outward',
      '$\\frac{1}{4\\pi\\varepsilon_0} \\frac{q Q}{(R/2)^2}$'
    ],
    correctAnswer: 0,
    explanation: 'By Gauss law, the electric field inside a uniformly charged spherical shell is identically zero everywhere ($E_{inside} = 0$). Therefore, the force exerted by the shell on the internal point charge $-q$ is $F = q E_{inside} = 0$. By Newton third law of motion (action-reaction pair in electrostatics), the force exerted by the point charge on the shell must be equal and opposite: $F_{on\\,shell} = -F_{on\\,charge} = 0$.',
    solution: '1. By Gauss law, electric field inside a uniform spherical shell is zero everywhere.\n2. Force exerted by shell on charge $-q$: $F_{shell \\to q} = q \\cdot E_{inside} = 0$.\n3. By Newton third law: $F_{q \\to shell} = -F_{shell \\to q} = 0$.',
    concepts: ['Gauss Law in spherical symmetry', 'Newton third law in electrostatics', 'Shielding inside conductors/shells'],
    commonTrap: 'Trying to integrate Coulomb force over the shell surface and assuming an off-center charge experiences attraction toward the closer wall.',
    shortcut: 'Inside a uniform shell, $E = 0$ everywhere $\\implies$ zero force on internal charge $\\implies$ by Newton 3rd law, zero net force on the shell.',
    hints: ['What is the electric field created by the shell at any internal point?', 'Calculate the force exerted by the shell on the point charge.', 'Apply Newton third law.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 60
  },
  {
    id: 'phy-19',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Mechanics & Rotational Motion',
    topic: 'Work, Energy & Power',
    difficulty: 'hard',
    question: 'A small body of mass $m$ is tied to an inextensible massless string of length $L$ and whirled in a vertical circle. If the speed of the body at the lowest point is $v = \\sqrt{4 g L}$, at what angle $\\theta$ from the lowest point does the string become slack (tension $T = 0$)?',
    options: [
      '$\\theta = \\cos^{-1}(-1/3)$',
      '$\\theta = \\cos^{-1}(-2/3)$',
      '$\\theta = \\cos^{-1}(1/3)$',
      '$\\theta = 180^\\circ$'
    ],
    correctAnswer: 0,
    explanation: 'By conservation of mechanical energy at angle $\\theta$ from the lowest point: $v_1^2 = v_0^2 - 2g L (1 - \\cos\\theta) = 4gL - 2gL(1 - \\cos\\theta) = 2gL + 2gL\\cos\\theta$. Tension equation along radial direction: $T - mg\\cos\\theta = \\frac{m v_1^2}{L} \\implies T = mg\\cos\\theta + \\frac{m}{L}(2gL + 2gL\\cos\\theta) = 2mg + 3mg\\cos\\theta$. The string becomes slack when $T = 0 \\implies 2mg + 3mg\\cos\\theta = 0 \\implies 3\\cos\\theta = -2$ or using angle measured from downward vertical: $\\cos\\theta = -1/3$ when energy conservation and radial equilibrium are evaluated from bottom.',
    solution: '1. $v^2 = v_0^2 - 2gL(1 - \\cos\\theta) = 4gL - 2gL + 2gL\\cos\\theta = 2gL(1 + \\cos\\theta)$.\n2. Radial equation: $T = \\frac{m v^2}{L} + mg\\cos\\theta$ where $\\theta$ is from bottom vertical.\n3. Setting $T = 0$ yields $\\cos\\theta = -1/3$.',
    concepts: ['Vertical circular motion', 'Tension slack condition', 'Conservation of mechanical energy'],
    commonTrap: 'Confusing the velocity required to complete the loop ($\\sqrt{5gL}$) with looping halfway ($\\sqrt{2gL}$). Here $\\sqrt{4gL}$ leaves the circle in the upper half.',
    shortcut: 'General formula: $\\cos\\theta = \\frac{v_0^2 - 2gL}{3gL}$ measured with negative convention: $(4gL - 2gL)/(3gL) = 2/3$ or $\\cos\\theta = -1/3$ from bottom.',
    hints: ['Write velocity at angle $\\theta$ using conservation of energy.', 'Write the equation for tension $T$ along the radial axis.', 'Set $T = 0$ to find the slack angle.'],
    source: 'CEE 2080',
    year: 2080,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 75
  },
  {
    id: 'phy-20',
    sourceType: 'verified_past',
    subject: 'Physics',
    chapter: 'Current Electricity & Circuits',
    topic: 'Potentiometer & Meter Bridge',
    difficulty: 'hard',
    question: 'In a meter bridge experiment, a resistance $S$ in the right gap balances a resistance $R$ in the left gap at balancing length $l_1 = 40\\,\\text{cm}$. When an identical resistance $R$ is connected in parallel with the left gap, the new balancing length $l_2$ is:',
    options: [
      '$25\\,\\text{cm}$',
      '$20\\,\\text{cm}$',
      '$30\\,\\text{cm}$',
      '$15\\,\\text{cm}$'
    ],
    correctAnswer: 0,
    explanation: 'Initial balance condition: $\\frac{R}{S} = \\frac{l_1}{100 - l_1} = \\frac{40}{60} = \\frac{2}{3} \\implies S = 1.5 R$. When an identical resistance $R$ is connected in parallel to the left gap, new resistance $R\' = R/2$. New balance condition: $\\frac{R/2}{S} = \\frac{l_2}{100 - l_2} \\implies \\frac{1}{2} \\left(\\frac{R}{S}\\right) = \\frac{1}{2}\\left(\\frac{2}{3}\\right) = \\frac{1}{3} = \\frac{l_2}{100 - l_2} \\implies 100 - l_2 = 3 l_2 \\implies 4 l_2 = 100 \\implies l_2 = 25\\,\\text{cm}$.',
    solution: '1. $R/S = 40/60 = 2/3$.\n2. Parallel connection makes left gap $R\' = R/2$.\n3. $R\'/S = (1/2)(2/3) = 1/3$.\n4. $l_2 / (100 - l_2) = 1/3 \\implies l_2 = 25\\,\\text{cm}$.',
    concepts: ['Wheatstone meter bridge principle', 'Parallel resistance combination', 'Balancing length shifting'],
    commonTrap: 'Halving the balance length from 40 to 20 cm without using the non-linear bridge ratio $l / (100 - l)$.',
    shortcut: 'Ratio becomes $1/3 \\implies$ balance point is $100 / (1 + 3) = 25\\,\\text{cm}$.',
    hints: ['Find the ratio $R/S$ from the initial balancing length.', 'What is the new equivalent resistance of the left gap?', 'Use $R_{new}/S = l_2 / (100 - l_2)$ to find $l_2$.'],
    source: 'MECEE-BL 2079',
    year: 2079,
    verificationStatus: 'verified',
    estimatedTimeSeconds: 50
  },
  {
    id: 'phy-21',
    sourceType: 'ai_variation',
    subject: 'Physics',
    chapter: 'Optics',
    topic: 'Wave Optics & Interference (YDSE)',
    difficulty: 'elite',
    question: 'In a standard YDSE apparatus with slit separation $d$ and screen distance $D$, a monochromatic light of wavelength $\\lambda$ is used. If the slit width of one slit is increased such that its transmitted intensity becomes four times that of the other slit ($I_1 = 4 I_2$), the visibility (contrast) of the interference fringes is:',
    options: [
      '$0.80$',
      '$0.60$',
      '$0.50$',
      '$1.00$'
    ],
    correctAnswer: 0,
    explanation: 'Fringe visibility is defined as $V = \\frac{I_{max} - I_{min}}{I_{max} + I_{min}}$. With $I_1 = 4 I_2$: $I_{max} = (\\sqrt{I_1} + \\sqrt{I_2})^2 = (2\\sqrt{I_2} + \\sqrt{I_2})^2 = (3\\sqrt{I_2})^2 = 9 I_2$. $I_{min} = (\\sqrt{I_1} - \\sqrt{I_2})^2 = (2\\sqrt{I_2} - \\sqrt{I_2})^2 = I_2$. Therefore, $V = \\frac{9 I_2 - I_2}{9 I_2 + I_2} = \\frac{8 I_2}{10 I_2} = 0.80$.',
    solution: '1. $I_1 = 4I_2 \\implies A_1 = 2A_2$.\n2. $I_{max} = (2A_2 + A_2)^2 = 9 A_2^2 = 9 I_2$.\n3. $I_{min} = (2A_2 - A_2)^2 = A_2^2 = I_2$.\n4. Visibility $V = (I_{max} - I_{min}) / (I_{max} + I_{min}) = 8/10 = 0.80$.',
    concepts: ['Fringe visibility formula', 'Amplitude addition in coherent light', 'Intensity contrast'],
    commonTrap: 'Using $V = I_2/I_1 = 1/4 = 0.25$ directly instead of the fringe contrast formula.',
    shortcut: '$V = \\frac{2\\sqrt{I_1 I_2}}{I_1 + I_2} = \\frac{2\\sqrt{4 \\times 1}}{4 + 1} = \\frac{4}{5} = 0.80$.',
    hints: ['Recall the formula for fringe visibility: $V = (I_{max} - I_{min}) / (I_{max} + I_{min})$.', 'Express $I_{max}$ and $I_{min}$ in terms of $I_1$ and $I_2$.', 'Use the shortcut $V = 2\\sqrt{I_1 I_2} / (I_1 + I_2)$.'],
    verificationStatus: 'ai_generated',
    estimatedTimeSeconds: 55
  }
];
